import type { Article, Source } from '../types';

export const sources: Source[] = [
  { id: 'hn', name: 'Hacker News', url: 'https://news.ycombinator.com', type: 'RSS', category: 'Developer Community', trustScore: 9, status: 'active', articlesCount: 3421, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '15 minutes' },
  { id: 'github-blog', name: 'GitHub Blog', url: 'https://github.blog', type: 'Official Blog', category: 'Developer Tools', trustScore: 10, status: 'active', articlesCount: 234, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '1 hour' },
  { id: 'arxiv', name: 'arXiv CS', url: 'https://arxiv.org', type: 'Research', category: 'Research', trustScore: 10, status: 'active', articlesCount: 8745, lastChecked: '2026-09-23T09:00:00Z', collectionFrequency: '6 hours' },
  { id: 'devto', name: 'Dev.to', url: 'https://dev.to', type: 'Developer Community', category: 'Software Engineering', trustScore: 7, status: 'active', articlesCount: 12034, lastChecked: '2026-09-23T10:15:00Z', collectionFrequency: '30 minutes' },
  { id: 'techcrunch', name: 'TechCrunch', url: 'https://techcrunch.com', type: 'RSS', category: 'Tech News', trustScore: 8, status: 'active', articlesCount: 5672, lastChecked: '2026-09-23T10:30:00Z', collectionFrequency: '1 hour' },
  { id: 'the-register', name: 'The Register', url: 'https://theregister.com', type: 'RSS', category: 'Tech News', trustScore: 8, status: 'active', articlesCount: 2341, lastChecked: '2026-09-23T09:45:00Z', collectionFrequency: '1 hour' },
  { id: 'infoq', name: 'InfoQ', url: 'https://infoq.com', type: 'RSS', category: 'Software Engineering', trustScore: 9, status: 'active', articlesCount: 3210, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '2 hours' },
  { id: 'vercel-blog', name: 'Vercel Blog', url: 'https://vercel.com/blog', type: 'Official Blog', category: 'Developer Tools', trustScore: 10, status: 'active', articlesCount: 187, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '6 hours' },
  { id: 'rust-blog', name: 'Rust Blog', url: 'https://blog.rust-lang.org', type: 'Official Blog', category: 'Languages', trustScore: 10, status: 'active', articlesCount: 98, lastChecked: '2026-09-23T08:00:00Z', collectionFrequency: '24 hours' },
  { id: 'openai-blog', name: 'OpenAI Blog', url: 'https://openai.com/blog', type: 'Official Blog', category: 'AI/ML', trustScore: 10, status: 'active', articlesCount: 124, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '6 hours' },
];

export const articles: Article[] = [
  {
    id: 'art-001',
    title: 'Anthropic Releases Claude 4 with 200K Context and Enhanced Reasoning',
    summary: 'Anthropic\'s latest Claude 4 model introduces a 200,000 token context window, dramatically improved reasoning capabilities, and new tool use features that enable complex multi-step agent workflows.',
    url: 'https://anthropic.com/blog/claude-4',
    imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80',
    source: sources[9],
    publishedAt: '2026-09-23T08:00:00Z',
    category: 'AI/ML',
    technologies: ['LLM Agents', 'RAG', 'AI'],
    readingTime: 8,
    clusterSize: 24,
    clusterId: 'cluster-claude4',
    aiSummary: {
      whatHappened: 'Anthropic released Claude 4, their most capable AI model to date, featuring a 200,000 token context window.',
      whyItMatters: 'This significantly expands what AI agents can process and reason about in a single interaction, enabling new enterprise use cases.',
      whoShouldCare: ['AI Engineers', 'Backend Developers', 'Researchers', 'Product Managers'],
      technologiesInvolved: ['LLM Agents', 'RAG', 'Transformer Architecture'],
      keyTakeaways: ['200K token context', 'Enhanced reasoning chains', 'Improved tool use API', 'Better code generation'],
    },
  },
  {
    id: 'art-002',
    title: 'Rust Joins the Linux Kernel: Production Drivers Now Available',
    summary: 'The Linux kernel has officially merged its first batch of production-ready Rust drivers, marking a historic milestone in systems programming and memory-safe OS development.',
    url: 'https://blog.rust-lang.org/linux-kernel',
    imageUrl: 'https://images.unsplash.com/photo-1629654291663-b91ad427698f?w=600&q=80',
    source: sources[8],
    publishedAt: '2026-09-22T14:30:00Z',
    category: 'Languages',
    technologies: ['Rust', 'Linux', 'Systems Programming'],
    readingTime: 12,
    clusterSize: 18,
    clusterId: 'cluster-rust-linux',
    aiSummary: {
      whatHappened: 'The Linux kernel officially merged production-ready Rust drivers for the first time.',
      whyItMatters: 'This validates Rust as a viable systems programming language for the world\'s most critical software infrastructure.',
      whoShouldCare: ['Systems Programmers', 'Kernel Developers', 'Security Engineers'],
      technologiesInvolved: ['Rust', 'Linux Kernel', 'Memory Safety'],
      keyTakeaways: ['First production Rust drivers merged', 'Proves memory safety at OS level', 'Sets precedent for future kernel work'],
    },
  },
  {
    id: 'art-003',
    title: 'Next.js 16 Introduces Partial Prerendering as Stable Feature',
    summary: 'Vercel has released Next.js 16 with Partial Prerendering (PPR) as a stable feature, enabling pages that combine static and dynamic content seamlessly without additional configuration.',
    url: 'https://nextjs.org/blog/next-16',
    imageUrl: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=600&q=80',
    source: sources[7],
    publishedAt: '2026-09-22T09:00:00Z',
    category: 'Frameworks',
    technologies: ['Next.js', 'React', 'TypeScript'],
    readingTime: 10,
    clusterSize: 31,
    clusterId: 'cluster-nextjs16',
  },
  {
    id: 'art-004',
    title: 'pgvector 1.0 Achieves Near-Pinecone Performance with HNSW Indexing',
    summary: 'The pgvector extension has reached version 1.0, with benchmark results showing HNSW index performance comparable to dedicated vector databases like Pinecone at a fraction of the operational cost.',
    url: 'https://github.com/pgvector/pgvector',
    imageUrl: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&q=80',
    source: sources[0],
    publishedAt: '2026-09-21T16:45:00Z',
    category: 'Databases',
    technologies: ['pgvector', 'PostgreSQL', 'AI', 'Semantic Search'],
    readingTime: 7,
    clusterSize: 12,
    clusterId: 'cluster-pgvector',
  },
  {
    id: 'art-005',
    title: 'Google DeepMind Releases Gemini 2 Ultra: Beats GPT-5 on Coding Benchmarks',
    summary: 'Google DeepMind\'s Gemini 2 Ultra model has achieved state-of-the-art results on HumanEval and SWE-bench benchmarks, demonstrating superior coding capabilities and multi-modal reasoning.',
    url: 'https://deepmind.google/gemini-2-ultra',
    imageUrl: 'https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=600&q=80',
    source: sources[4],
    publishedAt: '2026-09-21T11:00:00Z',
    category: 'AI/ML',
    technologies: ['LLM Agents', 'AI', 'Machine Learning'],
    readingTime: 9,
    clusterSize: 42,
    clusterId: 'cluster-gemini2',
  },
  {
    id: 'art-006',
    title: 'Bun 2.0 Ships: Now Faster Than Node.js by 5x on HTTP Benchmarks',
    summary: 'Bun 2.0 has been released with significant performance improvements, achieving 5x faster HTTP throughput than Node.js in independent benchmarks while maintaining full Node.js API compatibility.',
    url: 'https://bun.sh/blog/bun-v2',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80',
    source: sources[3],
    publishedAt: '2026-09-20T13:20:00Z',
    category: 'Developer Tools',
    technologies: ['Bun', 'JavaScript', 'Performance'],
    readingTime: 6,
    clusterSize: 16,
    clusterId: 'cluster-bun2',
  },
  {
    id: 'art-007',
    title: 'WebAssembly System Interface (WASI) 2.0 Becomes W3C Standard',
    summary: 'The W3C has officially adopted WASI 2.0 as a standard, bringing a stable API surface for WebAssembly modules to interact with operating system resources across cloud, edge, and embedded environments.',
    url: 'https://webassembly.org/wasi',
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&q=80',
    source: sources[0],
    publishedAt: '2026-09-19T10:00:00Z',
    category: 'Languages',
    technologies: ['WebAssembly', 'Rust', 'Systems'],
    readingTime: 8,
    clusterSize: 9,
    clusterId: 'cluster-wasi',
  },
  {
    id: 'art-008',
    title: 'GitHub Copilot Workspace Now Available: AI Writes Full Pull Requests',
    summary: 'GitHub has released Copilot Workspace to general availability, enabling developers to describe a task in natural language and have AI generate a complete, working pull request with tests.',
    url: 'https://github.blog/copilot-workspace',
    imageUrl: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=600&q=80',
    source: sources[1],
    publishedAt: '2026-09-19T08:00:00Z',
    category: 'Developer Tools',
    technologies: ['LLM Agents', 'AI', 'Developer Tools'],
    readingTime: 11,
    clusterSize: 28,
    clusterId: 'cluster-github-workspace',
  },
  {
    id: 'art-009',
    title: 'Kubernetes 2.0 Alpha: Simplified Networking and Native AI Workload Scheduling',
    summary: 'The CNCF has released the first alpha of Kubernetes 2.0, featuring a simplified networking model, built-in GPU/TPU scheduling for AI workloads, and reduced operational complexity for cluster administrators.',
    url: 'https://kubernetes.io/blog/kubernetes-2-alpha',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80',
    source: sources[6],
    publishedAt: '2026-09-18T12:00:00Z',
    category: 'DevOps',
    technologies: ['Kubernetes', 'Docker', 'Cloud', 'AI'],
    readingTime: 15,
    clusterSize: 19,
    clusterId: 'cluster-k8s2',
  },
  {
    id: 'art-010',
    title: 'Supabase Reaches 100k GitHub Stars, Announces Vector Search GA',
    summary: 'Supabase has reached 100,000 GitHub stars and simultaneously announced general availability of its built-in vector search powered by pgvector, making AI-enabled database queries trivial to implement.',
    url: 'https://supabase.com/blog/100k-stars',
    imageUrl: 'https://images.unsplash.com/photo-1614332287897-cdc485fa562d?w=600&q=80',
    source: sources[3],
    publishedAt: '2026-09-17T09:30:00Z',
    category: 'Databases',
    technologies: ['Supabase', 'pgvector', 'PostgreSQL'],
    readingTime: 5,
    clusterSize: 11,
    clusterId: 'cluster-supabase-100k',
  },
  {
    id: 'art-011',
    title: 'TypeScript 6.0 Introduces Pattern Matching and Native Type Macros',
    summary: 'Microsoft releases TypeScript 6.0 with long-awaited pattern matching syntax, type-level macros, and significant improvements to inference performance in large monorepos.',
    url: 'https://devblogs.microsoft.com/typescript/ts6',
    imageUrl: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=600&q=80',
    source: sources[6],
    publishedAt: '2026-09-16T14:00:00Z',
    category: 'Languages',
    technologies: ['TypeScript', 'JavaScript'],
    readingTime: 9,
    clusterSize: 22,
    clusterId: 'cluster-ts6',
  },
  {
    id: 'art-012',
    title: 'Meta Releases PyTorch 3.0 with Native CUDA Graph Support and 40% Speedup',
    summary: 'Meta AI open-sources PyTorch 3.0, featuring native CUDA graph support, a new distributed training API, and up to 40% faster training throughput on transformer models.',
    url: 'https://pytorch.org/blog/pytorch-3',
    imageUrl: 'https://images.unsplash.com/photo-1507146153580-69a1fe6d8aa1?w=600&q=80',
    source: sources[6],
    publishedAt: '2026-09-15T10:00:00Z',
    category: 'AI/ML',
    technologies: ['PyTorch', 'Machine Learning', 'CUDA'],
    readingTime: 11,
    clusterSize: 14,
    clusterId: 'cluster-pytorch3',
  },
];

export function getArticlesByCategory(category: string, limit?: number): Article[] {
  const filtered = articles.filter(a => a.category === category);
  return limit ? filtered.slice(0, limit) : filtered;
}

export function getArticlesByTech(tech: string, limit?: number): Article[] {
  const filtered = articles.filter(a => a.technologies.includes(tech));
  return limit ? filtered.slice(0, limit) : filtered;
}

export function getLatestArticles(limit = 10): Article[] {
  return [...articles]
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
    .slice(0, limit);
}
