import type { Article, Source } from '../types';

export const sourcesMap: Record<string, Source> = {
  'anthropic-news': { id: 'anthropic-news', name: 'Anthropic News', url: 'https://anthropic.com/news', type: 'Official Blog', category: 'AI/ML', trustScore: 10, status: 'active', articlesCount: 145, lastChecked: '2026-09-23T08:00:00Z', collectionFrequency: '4 hours' },
  'deepmind-blog': { id: 'deepmind-blog', name: 'Google DeepMind', url: 'https://deepmind.google', type: 'Official Blog', category: 'AI/ML', trustScore: 10, status: 'active', articlesCount: 310, lastChecked: '2026-09-23T09:00:00Z', collectionFrequency: '6 hours' },
  'openai-blog': { id: 'openai-blog', name: 'OpenAI Blog', url: 'https://openai.com/blog', type: 'Official Blog', category: 'AI/ML', trustScore: 10, status: 'active', articlesCount: 124, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '6 hours' },
  'rust-blog': { id: 'rust-blog', name: 'Rust Official Blog', url: 'https://blog.rust-lang.org', type: 'Official Blog', category: 'Languages', trustScore: 10, status: 'active', articlesCount: 98, lastChecked: '2026-09-23T08:00:00Z', collectionFrequency: '24 hours' },
  'vercel-blog': { id: 'vercel-blog', name: 'Vercel Blog', url: 'https://vercel.com/blog', type: 'Official Blog', category: 'Developer Tools', trustScore: 10, status: 'active', articlesCount: 187, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '6 hours' },
  'github-blog': { id: 'github-blog', name: 'GitHub Blog', url: 'https://github.blog', type: 'Official Blog', category: 'Developer Tools', trustScore: 10, status: 'active', articlesCount: 234, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '1 hour' },
  'bun-blog': { id: 'bun-blog', name: 'Bun Official Blog', url: 'https://bun.sh/blog', type: 'Official Blog', category: 'Developer Tools', trustScore: 9, status: 'active', articlesCount: 85, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '12 hours' },
  'supabase-blog': { id: 'supabase-blog', name: 'Supabase Blog', url: 'https://supabase.com/blog', type: 'Official Blog', category: 'Databases', trustScore: 9, status: 'active', articlesCount: 310, lastChecked: '2026-09-23T09:00:00Z', collectionFrequency: '6 hours' },
  'microsoft-dev': { id: 'microsoft-dev', name: 'Microsoft DevBlogs', url: 'https://devblogs.microsoft.com', type: 'Official Blog', category: 'Languages', trustScore: 10, status: 'active', articlesCount: 1200, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '4 hours' },
  'pytorch-blog': { id: 'pytorch-blog', name: 'PyTorch Blog', url: 'https://pytorch.org/blog', type: 'Official Blog', category: 'AI/ML', trustScore: 10, status: 'active', articlesCount: 220, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '12 hours' },
  'kubernetes-io': { id: 'kubernetes-io', name: 'Kubernetes Official Blog', url: 'https://kubernetes.io/blog', type: 'Official Blog', category: 'DevOps', trustScore: 10, status: 'active', articlesCount: 450, lastChecked: '2026-09-23T09:15:00Z', collectionFrequency: '12 hours' },
  'techcrunch': { id: 'techcrunch', name: 'TechCrunch', url: 'https://techcrunch.com', type: 'RSS', category: 'Tech News', trustScore: 8, status: 'active', articlesCount: 5672, lastChecked: '2026-09-23T10:30:00Z', collectionFrequency: '1 hour' },
  'the-verge': { id: 'the-verge', name: 'The Verge', url: 'https://theverge.com', type: 'RSS', category: 'Tech News', trustScore: 9, status: 'active', articlesCount: 4120, lastChecked: '2026-09-23T10:10:00Z', collectionFrequency: '1 hour' },
  'mit-tech-review': { id: 'mit-tech-review', name: 'MIT Technology Review', url: 'https://technologyreview.com', type: 'Official Blog', category: 'Emerging Tech', trustScore: 10, status: 'active', articlesCount: 1420, lastChecked: '2026-09-23T10:40:00Z', collectionFrequency: '2 hours' },
  'the-register': { id: 'the-register', name: 'The Register', url: 'https://theregister.com', type: 'RSS', category: 'Tech News', trustScore: 8, status: 'active', articlesCount: 2341, lastChecked: '2026-09-23T09:45:00Z', collectionFrequency: '1 hour' },
  'infoq': { id: 'infoq', name: 'InfoQ', url: 'https://infoq.com', type: 'RSS', category: 'Software Engineering', trustScore: 9, status: 'active', articlesCount: 3210, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '2 hours' },
  'hn': { id: 'hn', name: 'Hacker News', url: 'https://news.ycombinator.com', type: 'RSS', category: 'Developer Community', trustScore: 9, status: 'active', articlesCount: 3421, lastChecked: '2026-09-23T10:00:00Z', collectionFrequency: '15 minutes' },
  'devto': { id: 'devto', name: 'Dev.to', url: 'https://dev.to', type: 'Developer Community', category: 'Software Engineering', trustScore: 7, status: 'active', articlesCount: 12034, lastChecked: '2026-09-23T10:15:00Z', collectionFrequency: '30 minutes' },
  'arxiv': { id: 'arxiv', name: 'arXiv CS', url: 'https://arxiv.org', type: 'Research', category: 'Research', trustScore: 10, status: 'active', articlesCount: 8745, lastChecked: '2026-09-23T09:00:00Z', collectionFrequency: '6 hours' },
  'nature-physics': { id: 'nature-physics', name: 'Nature Physics', url: 'https://nature.com/nphys', type: 'Research', category: 'Quantum', trustScore: 10, status: 'active', articlesCount: 420, lastChecked: '2026-09-23T07:30:00Z', collectionFrequency: '24 hours' },
  'ieee-spectrum': { id: 'ieee-spectrum', name: 'IEEE Spectrum', url: 'https://spectrum.ieee.org', type: 'Research', category: 'Emerging Tech', trustScore: 10, status: 'active', articlesCount: 910, lastChecked: '2026-09-23T08:15:00Z', collectionFrequency: '12 hours' },
  'lwn-net': { id: 'lwn-net', name: 'LWN.net', url: 'https://lwn.net', type: 'RSS', category: 'Systems', trustScore: 10, status: 'active', articlesCount: 1150, lastChecked: '2026-09-23T09:00:00Z', collectionFrequency: '12 hours' },
  'kernel-docs': { id: 'kernel-docs', name: 'Kernel.org Documentation', url: 'https://docs.kernel.org', type: 'Official Documentation', category: 'Systems', trustScore: 10, status: 'active', articlesCount: 120, lastChecked: '2026-09-23T08:00:00Z', collectionFrequency: '24 hours' },
  'github-pgvector': { id: 'github-pgvector', name: 'GitHub Open Source', url: 'https://github.com/pgvector/pgvector', type: 'Open Source', category: 'Databases', trustScore: 10, status: 'active', articlesCount: 45, lastChecked: '2026-09-23T09:00:00Z', collectionFrequency: '12 hours' },
  'bytecode-alliance': { id: 'bytecode-alliance', name: 'Bytecode Alliance', url: 'https://bytecodealliance.org', type: 'Official Blog', category: 'Languages', trustScore: 10, status: 'active', articlesCount: 65, lastChecked: '2026-09-23T08:00:00Z', collectionFrequency: '24 hours' },
};

export const sources: Source[] = Object.values(sourcesMap);

export const articles: Article[] = [
  {
    id: 'art-001',
    title: 'Anthropic Introduces Computer Use with Claude 3.5 Sonnet',
    summary: 'Anthropic announces public beta of computer use with upgraded Claude 3.5 Sonnet, allowing AI models to operate computer interfaces directly, execute clicks, type, and automate multi-step developer workflows.',
    url: 'https://www.anthropic.com/news/3-5-models-and-computer-use',
    imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80',
    source: sourcesMap['anthropic-news'],
    publishedAt: '2024-10-22T14:00:00Z',
    category: 'AI/ML',
    technologies: ['LLM Agents', 'Computer Use', 'AI'],
    readingTime: 6,
    clusterSize: 18,
    clusterId: 'cluster-claude4',
    aiSummary: {
      whatHappened: 'Anthropic announced Computer Use capabilities for Claude 3.5 Sonnet, enabling the AI to view screens and operate desktop software.',
      whyItMatters: 'Transitions AI from passive text generation to active agentic computer execution across arbitrary desktop and web applications.',
      whoShouldCare: ['AI Engineers', 'Backend Developers', 'Automation Engineers', 'Product Managers'],
      technologiesInvolved: ['LLM Agents', 'Computer Vision', 'Tool Use APIs'],
      keyTakeaways: ['Direct OS and screen control', 'Public beta API for developers', 'Automates repetitive multi-app tasks', 'Claude 3.5 Sonnet upgrade'],
    },
  },
  {
    id: 'art-002',
    title: 'Rust Infrastructure in the Linux Kernel Mainline Tree',
    summary: 'The Linux kernel mainline tree integrates memory-safe Rust abstractions and initial subsystem device drivers, opening systems programming to verified memory safety guarantees.',
    url: 'https://docs.kernel.org/rust/index.html',
    imageUrl: 'https://images.unsplash.com/photo-1629654291663-b91ad427698f?w=600&q=80',
    source: sourcesMap['kernel-docs'],
    publishedAt: '2024-09-18T10:30:00Z',
    category: 'Languages',
    technologies: ['Rust', 'Linux', 'Systems Programming'],
    readingTime: 12,
    clusterSize: 15,
    clusterId: 'cluster-rust-linux',
    aiSummary: {
      whatHappened: 'The Linux kernel officially adopted Rust for driver development and core subsystem abstractions.',
      whyItMatters: 'Provides hardware-level memory safety without garbage collection overhead, addressing historical memory bugs in operating systems.',
      whoShouldCare: ['Systems Programmers', 'Kernel Developers', 'Security Engineers'],
      technologiesInvolved: ['Rust', 'Linux Kernel', 'Memory Safety'],
      keyTakeaways: ['Official kernel documentation live', 'Eliminates spatial memory vulnerabilities', 'Production device drivers entering mainline'],
    },
  },
  {
    id: 'art-003',
    title: 'Next.js 15 General Availability: React 19 Support and Async Request APIs',
    summary: 'Vercel releases Next.js 15 with full React 19 support, Turbopack for development, Async Request APIs, and improved static/dynamic optimization.',
    url: 'https://nextjs.org/blog/next-15',
    imageUrl: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=600&q=80',
    source: sourcesMap['vercel-blog'],
    publishedAt: '2024-10-21T16:00:00Z',
    category: 'Frameworks',
    technologies: ['Next.js', 'React', 'TypeScript'],
    readingTime: 8,
    clusterSize: 22,
    clusterId: 'cluster-nextjs15',
  },
  {
    id: 'art-004',
    title: 'pgvector: Open-Source Vector Similarity Search for PostgreSQL',
    summary: 'The pgvector extension brings HNSW and IVFFlat vector indexing to PostgreSQL, enabling production-grade semantic search and AI embedding storage at massive scale.',
    url: 'https://github.com/pgvector/pgvector',
    imageUrl: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&q=80',
    source: sourcesMap['github-pgvector'],
    publishedAt: '2024-09-10T12:00:00Z',
    category: 'Databases',
    technologies: ['pgvector', 'PostgreSQL', 'AI', 'Semantic Search'],
    readingTime: 7,
    clusterSize: 12,
    clusterId: 'cluster-pgvector',
  },
  {
    id: 'art-005',
    title: 'Google DeepMind Gemini 1.5 Pro: Next-Generation Multi-Modal Reasoning',
    summary: 'Google DeepMind introduces Gemini 1.5 Pro featuring a breakthrough 2-million token context window, advanced multimodal processing, and state-of-the-art code synthesis.',
    url: 'https://deepmind.google/technologies/gemini/',
    imageUrl: 'https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=600&q=80',
    source: sourcesMap['deepmind-blog'],
    publishedAt: '2024-09-24T09:00:00Z',
    category: 'AI/ML',
    technologies: ['LLM Agents', 'AI', 'Machine Learning'],
    readingTime: 9,
    clusterSize: 32,
    clusterId: 'cluster-gemini',
  },
  {
    id: 'art-006',
    title: 'Bun 1.0: Fast All-in-One JavaScript & TypeScript Runtime',
    summary: 'Bun 1.0 officially ships as a drop-in replacement for Node.js, featuring a native bundler, transpiler, test runner, and high-speed package manager.',
    url: 'https://bun.sh/blog/bun-v1.0',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80',
    source: sourcesMap['bun-blog'],
    publishedAt: '2024-08-15T11:00:00Z',
    category: 'Developer Tools',
    technologies: ['Bun', 'JavaScript', 'Performance'],
    readingTime: 6,
    clusterSize: 16,
    clusterId: 'cluster-bun',
  },
  {
    id: 'art-007',
    title: 'WebAssembly System Interface (WASI) 0.2 Specification Released',
    summary: 'Bytecode Alliance announces the WASI 0.2 release, establishing component model standards for running WebAssembly portably across cloud, edge, and serverless runtimes.',
    url: 'https://bytecodealliance.org/articles/wasi-0.2',
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&q=80',
    source: sourcesMap['bytecode-alliance'],
    publishedAt: '2024-08-10T14:00:00Z',
    category: 'Languages',
    technologies: ['WebAssembly', 'Rust', 'Systems'],
    readingTime: 8,
    clusterSize: 9,
    clusterId: 'cluster-wasi',
  },
  {
    id: 'art-008',
    title: 'GitHub Copilot Workspace: AI-Assisted Developer Environment',
    summary: 'GitHub unveils Copilot Workspace, enabling developers to brainstorm, plan, build, test, and debug code from natural language task specifications.',
    url: 'https://github.blog/news-insights/product-news/github-copilot-workspace/',
    imageUrl: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=600&q=80',
    source: sourcesMap['github-blog'],
    publishedAt: '2024-09-05T08:00:00Z',
    category: 'Developer Tools',
    technologies: ['LLM Agents', 'AI', 'Developer Tools'],
    readingTime: 11,
    clusterSize: 28,
    clusterId: 'cluster-github-workspace',
  },
  {
    id: 'art-009',
    title: 'Kubernetes 1.31 Release: Storage and Networking Enhancements',
    summary: 'The Kubernetes project releases version 1.31, stabilizing in-tree volume plugins, improving cgroup v2 support, and streamlining container orchestration.',
    url: 'https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80',
    source: sourcesMap['kubernetes-io'],
    publishedAt: '2024-08-13T12:00:00Z',
    category: 'DevOps',
    technologies: ['Kubernetes', 'Docker', 'Cloud', 'AI'],
    readingTime: 10,
    clusterSize: 19,
    clusterId: 'cluster-k8s',
  },
  {
    id: 'art-010',
    title: 'Supabase Vector: Managing AI Embeddings at Scale in Postgres',
    summary: 'Supabase announces managed vector indexing and pgvector integration, allowing developers to query embeddings directly alongside transactional relational data.',
    url: 'https://supabase.com/blog/openai-embeddings-postgres-vector',
    imageUrl: 'https://images.unsplash.com/photo-1614332287897-cdc485fa562d?w=600&q=80',
    source: sourcesMap['supabase-blog'],
    publishedAt: '2024-07-20T10:00:00Z',
    category: 'Databases',
    technologies: ['Supabase', 'pgvector', 'PostgreSQL'],
    readingTime: 5,
    clusterSize: 11,
    clusterId: 'cluster-supabase',
  },
  {
    id: 'art-011',
    title: 'Announcing TypeScript 5.6: Iterator Helpers and Strict Checks',
    summary: 'Microsoft releases TypeScript 5.6 featuring disallowed nullish checks, built-in iterator helper functions, and improved type inference speed in large monorepos.',
    url: 'https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/',
    imageUrl: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=600&q=80',
    source: sourcesMap['microsoft-dev'],
    publishedAt: '2024-09-09T15:00:00Z',
    category: 'Languages',
    technologies: ['TypeScript', 'JavaScript'],
    readingTime: 7,
    clusterSize: 22,
    clusterId: 'cluster-ts',
  },
  {
    id: 'art-012',
    title: 'PyTorch 2.4 Released with TorchDynamo and AOTInductor Enhancements',
    summary: 'PyTorch 2.4 launches with native Python 3.12 support, TorchDynamo compiler improvements, and optimized distributed training across GPU clusters.',
    url: 'https://pytorch.org/blog/pytorch-2-4/',
    imageUrl: 'https://images.unsplash.com/photo-1507146153580-69a1fe6d8aa1?w=600&q=80',
    source: sourcesMap['pytorch-blog'],
    publishedAt: '2024-07-24T10:00:00Z',
    category: 'AI/ML',
    technologies: ['PyTorch', 'Machine Learning', 'CUDA'],
    readingTime: 11,
    clusterSize: 14,
    clusterId: 'cluster-pytorch',
  },
];

export function getArticlesByCategory(category: string, limit?: number): Article[] {
  const filtered = articles.filter(a => a.category === category);
  return limit ? filtered.slice(0, limit) : filtered;
}

export function getArticlesByTech(tech: string, limit?: number): Article[] {
  const filtered = articles.filter(a => a.technologies.includes(tech));
  return limit ? filtered.slice(0, limit) : filtered;
}

export function getLatestArticles(limit = 10): Article[] {
  return [...articles]
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
    .slice(0, limit);
}
