import type { ResearchPaper } from '../types';

export const researchPapers: ResearchPaper[] = [
  {
    id: 'paper-001',
    title: 'Constitutional AI: Harmlessness from AI Feedback with Scalable Oversight',
    authors: ['Yuntao Bai', 'Saurav Kadavath', 'Amanda Askell', 'John Schulman'],
    publishedAt: '2026-08-14',
    summary: 'A method for training harmless AI assistants through self-improvement without human feedback on harms, using a set of constitutional principles to critique and revise model responses.',
    topics: ['AI Safety', 'Alignment', 'Reinforcement Learning', 'LLMs'],
    technologies: ['LLM Agents', 'RLHF', 'Transformers'],
    source: 'arXiv CS.AI',
    sourceUrl: 'https://arxiv.org/abs/2212.08073',
    doi: '10.48550/arXiv.2212.08073',
    citations: 1420,
  },
  {
    id: 'paper-002',
    title: 'FlashAttention-3: Fast and Memory-Efficient Exact Attention with Asynchronous Computation',
    authors: ['Tri Dao', 'Daniel Haziza', 'Francisco Massa', 'Grigory Perepelitsyn'],
    publishedAt: '2026-07-28',
    summary: 'FlashAttention-3 exploits modern GPU tensor core capabilities, utilizing hardware overlap between tensor cores and memory operations to achieve up to 850 TFLOPs/s on Hopper GPUs.',
    topics: ['Hardware Acceleration', 'Transformers', 'GPU Computing', 'Efficiency'],
    technologies: ['CUDA', 'PyTorch', 'GPU Clusters', 'Transformers'],
    source: 'arXiv CS.LG',
    sourceUrl: 'https://arxiv.org/abs/2407.08608',
    doi: '10.48550/arXiv.2407.08608',
    citations: 890,
  },
  {
    id: 'paper-003',
    title: 'Formal Verification of Memory-Safe Operating System Components in Rust',
    authors: ['Markus Weber', 'Elena Rostova', 'David Chen', 'Sarah Lin'],
    publishedAt: '2026-09-02',
    summary: 'Demonstrates end-to-end automated verification of concurrency and memory safety invariants in kernel-level Rust drivers using SMT-based deductive verification frameworks.',
    topics: ['Systems Security', 'Formal Methods', 'Kernel Architecture'],
    technologies: ['Rust', 'SMT Solvers', 'Linux', 'Formal Verification'],
    source: 'IEEE Symposium on Security & Privacy',
    sourceUrl: 'https://ieee-security.org/papers/2026/rust-verification',
    doi: '10.1109/SP.2026.1044',
    citations: 156,
  },
  {
    id: 'paper-004',
    title: 'GraphRAG: Unlocking LLM Discovery on Narrative Private Corpora',
    authors: ['Darren Edge', 'Ha Trinh', 'Newman Cheng', 'Joshua Bradley'],
    publishedAt: '2026-06-18',
    summary: 'Combines Knowledge Graphs with Retrieval-Augmented Generation to synthesize insights across large text corpora, addressing catastrophic failure modes of naive vector search.',
    topics: ['Knowledge Graphs', 'RAG', 'Information Retrieval', 'NLP'],
    technologies: ['GraphRAG', 'Vector Databases', 'Neo4j', 'LLM Agents'],
    source: 'ACM SIGKDD 2026',
    sourceUrl: 'https://arxiv.org/abs/2404.16130',
    doi: '10.1145/3637528.3671824',
    citations: 630,
  },
  {
    id: 'paper-005',
    title: 'Fault-Tolerant Quantum Error Correction with Surface Codes under 0.1% Physical Noise',
    authors: ['Jonathan Martinez', 'Aiko Tanaka', 'Devon Vance'],
    publishedAt: '2026-08-30',
    summary: 'Real-time decoding algorithms achieving sub-microsecond syndrome processing in topological surface codes, demonstrating viable logical qubit scaling beyond the break-even threshold.',
    topics: ['Quantum Computing', 'Quantum Error Correction', 'Surface Codes'],
    technologies: ['Quantum Computing', 'Qiskit', 'FPGA Decoders'],
    source: 'Nature Quantum Information',
    sourceUrl: 'https://nature.com/articles/s41534-026-00912-x',
    doi: '10.1038/s41534-026-00912-x',
    citations: 215,
  },
  {
    id: 'paper-006',
    title: 'Zero-Knowledge Succinct Non-Interactive Proofs for Cross-Chain Rollup Finality',
    authors: ['Alexei Petrov', 'Maria Santos', 'Kavita Sundaram'],
    publishedAt: '2026-05-12',
    summary: 'A sub-linear recursive zk-SNARK prover protocol reducing cross-chain verification latency from 15 minutes to under 4 seconds while preserving zero-knowledge security.',
    topics: ['Cryptography', 'Zero-Knowledge Proofs', 'Distributed Systems'],
    technologies: ['ZK-Rollups', 'Circom', 'Rust', 'Ethereum'],
    source: 'IACR Cryptology ePrint Archive',
    sourceUrl: 'https://eprint.iacr.org/2026/894',
    doi: '10.1007/978-3-031-64879-3_14',
    citations: 342,
  },
];
