import type { Skill, CareerPath } from '../types';

export const skills: Skill[] = [
  {
    id: 'skill-1',
    name: 'Agentic Workflow Orchestration',
    category: 'AI/ML Engineering',
    demand: 'Very High',
    growth: 145,
    relatedTechs: ['LangChain', 'AutoGPT', 'LlamaIndex', 'Python'],
    roles: ['AI Engineer', 'Automation Architect', 'Full Stack AI Developer'],
  },
  {
    id: 'skill-2',
    name: 'Rust Systems Programming',
    category: 'Systems & Backend',
    demand: 'Very High',
    growth: 82,
    relatedTechs: ['Rust', 'WebAssembly', 'Linux Kernel', 'Tokio'],
    roles: ['Systems Engineer', 'Security Engineer', 'Infrastructure Developer'],
  },
  {
    id: 'skill-3',
    name: 'Retrieval-Augmented Generation (RAG)',
    category: 'AI/ML Engineering',
    demand: 'Very High',
    growth: 110,
    relatedTechs: ['pgvector', 'Pinecone', 'Embeddings', 'OpenAI'],
    roles: ['Machine Learning Engineer', 'Data Scientist', 'Search Specialist'],
  },
  {
    id: 'skill-4',
    name: 'Next.js App Router & Server Actions',
    category: 'Frontend & Full Stack',
    demand: 'High',
    growth: 44,
    relatedTechs: ['Next.js', 'React 19', 'TypeScript', 'Tailwind CSS'],
    roles: ['Frontend Engineer', 'Full Stack Developer', 'Web App Architect'],
  },
  {
    id: 'skill-5',
    name: 'Cloud-Native eBPF Observability',
    category: 'DevOps & Infrastructure',
    demand: 'High',
    growth: 68,
    relatedTechs: ['eBPF', 'Cilium', 'Kubernetes', 'Prometheus'],
    roles: ['Site Reliability Engineer (SRE)', 'Platform Engineer', 'DevOps Specialist'],
  },
  {
    id: 'skill-6',
    name: 'PostgreSQL Vector Search & Indexing',
    category: 'Databases & Data Engineering',
    demand: 'High',
    growth: 92,
    relatedTechs: ['pgvector', 'PostgreSQL', 'HNSW', 'IVFFlat'],
    roles: ['Database Administrator', 'Data Engineer', 'Backend Engineer'],
  },
];

export const careerPaths: CareerPath[] = [
  {
    id: 'ai-ml-engineering',
    name: 'AI/ML Engineering',
    description: 'Design, build, and deploy production machine learning models, LLM systems, fine-tuning pipelines, and agentic workflows.',
    icon: 'Brain',
    skills: ['Model Fine-Tuning', 'Agentic Workflows', 'Vector Databases', 'PyTorch', 'Prompt Evaluation'],
    technologies: ['PyTorch', 'Hugging Face', 'LangChain', 'vLLM', 'pgvector'],
    averageSalary: '$165,000 - $240,000',
    growthRate: 48,
  },
  {
    id: 'frontend-development',
    name: 'Frontend Development',
    description: 'Create high-performance, accessible, and reactive user interfaces using modern component systems and web standards.',
    icon: 'Layout',
    skills: ['React 19 & Server Components', 'TypeScript', 'Tailwind CSS', 'Performance Profiling', 'Web Vitals'],
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Vite'],
    averageSalary: '$120,000 - $185,000',
    growthRate: 22,
  },
  {
    id: 'backend-development',
    name: 'Backend Development',
    description: 'Architect resilient APIs, microservices, distributed data pipelines, and real-time transaction processing systems.',
    icon: 'Server',
    skills: ['System Design', 'Concurrent Systems', 'Database Optimization', 'Message Queues', 'Security & Auth'],
    technologies: ['Node.js / NestJS', 'Go', 'Rust', 'PostgreSQL', 'Redis'],
    averageSalary: '$135,000 - $195,000',
    growthRate: 28,
  },
  {
    id: 'devops-cloud',
    name: 'DevOps & Platform Engineering',
    description: 'Build automated continuous integration pipelines, infrastructure as code, container orchestration, and observability platforms.',
    icon: 'Terminal',
    skills: ['Kubernetes Orchestration', 'Infrastructure as Code', 'eBPF Observability', 'CI/CD Pipelines', 'Cloud Security'],
    technologies: ['Kubernetes', 'Terraform', 'Docker', 'AWS / GCP', 'eBPF'],
    averageSalary: '$140,000 - $210,000',
    growthRate: 35,
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity & Application Security',
    description: 'Protect enterprise infrastructure, analyze vulnerabilities, implement zero-trust architectures, and secure supply chains.',
    icon: 'Shield',
    skills: ['Threat Modeling', 'Zero Trust Architecture', 'Penetration Testing', 'Cryptography', 'Memory Safety Auditing'],
    technologies: ['Rust', 'eBPF', 'Wazuh', 'HashiCorp Vault', 'WireGuard'],
    averageSalary: '$145,000 - $220,000',
    growthRate: 40,
  },
  {
    id: 'data-science',
    name: 'Data Science & Analytics',
    description: 'Extract statistical insights, build predictive models, design experiment frameworks, and build data lakes.',
    icon: 'BarChart3',
    skills: ['Exploratory Data Analysis', 'Statistical Modeling', 'Feature Engineering', 'Data Warehousing', 'BI Visualization'],
    technologies: ['Python', 'DuckDB', 'Apache Spark', 'Polars', 'dbt'],
    averageSalary: '$130,000 - $190,000',
    growthRate: 26,
  },
];
