import type { Skill, CareerPath } from '../types';

export const skills: Skill[] = [
  // Rising & In-Demand Skills
  {
    id: 'skill-1',
    name: 'Agentic Workflow Orchestration',
    category: 'AI/ML Engineering',
    demand: 'Very High',
    growth: 145,
    trendDirection: 'rising',
    relatedTechs: ['LangChain', 'AutoGPT', 'LlamaIndex', 'Python'],
    roles: ['AI Engineer', 'Automation Architect', 'Full Stack AI Developer'],
  },
  {
    id: 'skill-2',
    name: 'Rust Systems Programming',
    category: 'Systems & Backend',
    demand: 'Very High',
    growth: 82,
    trendDirection: 'rising',
    relatedTechs: ['Rust', 'WebAssembly', 'Linux Kernel', 'Tokio'],
    roles: ['Systems Engineer', 'Security Engineer', 'Infrastructure Developer'],
  },
  {
    id: 'skill-3',
    name: 'Retrieval-Augmented Generation (RAG)',
    category: 'AI/ML Engineering',
    demand: 'Very High',
    growth: 110,
    trendDirection: 'rising',
    relatedTechs: ['pgvector', 'Pinecone', 'Embeddings', 'OpenAI'],
    roles: ['Machine Learning Engineer', 'Data Scientist', 'Search Specialist'],
  },
  {
    id: 'skill-4',
    name: 'Next.js App Router & Server Actions',
    category: 'Frontend & Full Stack',
    demand: 'High',
    growth: 44,
    trendDirection: 'rising',
    relatedTechs: ['Next.js', 'React 19', 'TypeScript', 'Tailwind CSS'],
    roles: ['Frontend Engineer', 'Full Stack Developer', 'Web App Architect'],
  },
  {
    id: 'skill-5',
    name: 'Cloud-Native eBPF Observability',
    category: 'DevOps & Infrastructure',
    demand: 'High',
    growth: 68,
    trendDirection: 'rising',
    relatedTechs: ['eBPF', 'Cilium', 'Kubernetes', 'Prometheus'],
    roles: ['Site Reliability Engineer (SRE)', 'Platform Engineer', 'DevOps Specialist'],
  },
  {
    id: 'skill-6',
    name: 'PostgreSQL Vector Search & Indexing',
    category: 'Databases & Data Engineering',
    demand: 'High',
    growth: 92,
    trendDirection: 'rising',
    relatedTechs: ['pgvector', 'PostgreSQL', 'HNSW', 'IVFFlat'],
    roles: ['Database Administrator', 'Data Engineer', 'Backend Engineer'],
  },

  // Falling & Cooling Skills (Sunset & Legacy Migration Radar)
  {
    id: 'skill-falling-1',
    name: 'Legacy jQuery & Direct DOM Scripting',
    category: 'Frontend & Full Stack',
    demand: 'Sunset',
    growth: -48,
    trendDirection: 'falling',
    relatedTechs: ['jQuery', 'DOM API', 'HTML5'],
    roles: ['Legacy Web Maintainer', 'WordPress Integrator'],
    declineReason: 'Modern reactive component frameworks and native browser Fetch/DOM APIs have made jQuery obsolete in modern codebases.',
    replacedBy: ['React 19', 'TypeScript', 'Modern Web APIs'],
  },
  {
    id: 'skill-falling-2',
    name: 'AngularJS 1.x Architecture & Digest Cycles',
    category: 'Frontend & Full Stack',
    demand: 'Sunset',
    growth: -59,
    trendDirection: 'falling',
    relatedTechs: ['AngularJS', 'Bower', 'Gulp'],
    roles: ['Enterprise Migration Specialist', 'Legacy Frontend Dev'],
    declineReason: 'Official EOL, lack of TypeScript-first ergonomics, and severe security maintenance overhead.',
    replacedBy: ['Modern Angular (v17+)', 'Next.js App Router', 'Vue 3'],
  },
  {
    id: 'skill-falling-3',
    name: 'Objective-C iOS App Maintenance',
    category: 'Mobile & Systems',
    demand: 'Declining',
    growth: -44,
    trendDirection: 'falling',
    relatedTechs: ['Objective-C', 'CocoaPods', 'Xcode'],
    roles: ['Legacy iOS Maintenance Developer'],
    declineReason: 'Apple platform development has transitioned 90%+ to Swift and SwiftUI; modern Apple SDKs mandate Swift.',
    replacedBy: ['Swift', 'SwiftUI', 'Kotlin Multiplatform'],
  },
  {
    id: 'skill-falling-4',
    name: 'SOAP & XML Web Services Protocol',
    category: 'Systems & Backend',
    demand: 'Sunset',
    growth: -52,
    trendDirection: 'falling',
    relatedTechs: ['SOAP', 'WSDL', 'XML', 'Apache Axis'],
    roles: ['Enterprise Integration Engineer'],
    declineReason: 'Heavy XML bandwidth overhead and tooling complexity replaced universally by RESTful JSON, GraphQL, and binary gRPC.',
    replacedBy: ['RESTful APIs', 'gRPC', 'GraphQL'],
  },
  {
    id: 'skill-falling-5',
    name: 'Cordova & PhoneGap Hybrid Mobile Wrappers',
    category: 'Mobile & Systems',
    demand: 'Declining',
    growth: -50,
    trendDirection: 'falling',
    relatedTechs: ['Cordova', 'PhoneGap', 'WebView'],
    roles: ['Hybrid Mobile Developer'],
    declineReason: 'WebView hybrid wrappers suffer from performance lag and jank compared to compiled native platforms like React Native and Flutter.',
    replacedBy: ['React Native', 'Flutter', 'Capacitor'],
  },
  {
    id: 'skill-falling-6',
    name: 'Procedural PHP 5.x & Monolithic Scripting',
    category: 'Systems & Backend',
    demand: 'Cooling',
    growth: -36,
    trendDirection: 'falling',
    relatedTechs: ['PHP 5', 'MySQL 5.6', 'Apache'],
    roles: ['Legacy CMS Webmaster'],
    declineReason: 'Unpatched security risks, lack of type safety, and absent async runtime capabilities.',
    replacedBy: ['Modern PHP 8.3 / Laravel', 'Node.js', 'Go'],
  },
  {
    id: 'skill-falling-7',
    name: 'Apache Ant & XML Build Scripting',
    category: 'DevOps & Infrastructure',
    demand: 'Sunset',
    growth: -62,
    trendDirection: 'falling',
    relatedTechs: ['Apache Ant', 'XML', 'Ivy'],
    roles: ['Legacy Build Engineer'],
    declineReason: 'Procedural XML pipelines have been completely replaced by declarative build systems, Gradle, and modern CI/CD.',
    replacedBy: ['GitHub Actions', 'Gradle', 'Docker'],
  },
];

export const risingSkills = skills.filter((s) => (s.trendDirection || 'rising') === 'rising');
export const fallingSkills = skills.filter((s) => s.trendDirection === 'falling');

export const careerPaths: CareerPath[] = [
  {
    id: 'ai-ml-engineering',
    name: 'AI/ML Engineering',
    description: 'Design, build, and deploy production machine learning models, LLM systems, fine-tuning pipelines, and agentic workflows.',
    icon: 'Brain',
    skills: ['Model Fine-Tuning', 'Agentic Workflows', 'Vector Databases', 'PyTorch', 'Prompt Evaluation'],
    technologies: ['PyTorch', 'Hugging Face', 'LangChain', 'vLLM', 'pgvector'],
    averageSalary: '$165,000 - $240,000',
    growthRate: 48,
  },
  {
    id: 'frontend-development',
    name: 'Frontend Development',
    description: 'Create high-performance, accessible, and reactive user interfaces using modern component systems and web standards.',
    icon: 'Layout',
    skills: ['React 19 & Server Components', 'TypeScript', 'Tailwind CSS', 'Performance Profiling', 'Web Vitals'],
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Vite'],
    averageSalary: '$120,000 - $185,000',
    growthRate: 22,
  },
  {
    id: 'backend-development',
    name: 'Backend Development',
    description: 'Architect resilient APIs, microservices, distributed data pipelines, and real-time transaction processing systems.',
    icon: 'Server',
    skills: ['System Design', 'Concurrent Systems', 'Database Optimization', 'Message Queues', 'Security & Auth'],
    technologies: ['Node.js / NestJS', 'Go', 'Rust', 'PostgreSQL', 'Redis'],
    averageSalary: '$135,000 - $195,000',
    growthRate: 28,
  },
  {
    id: 'devops-cloud',
    name: 'DevOps & Platform Engineering',
    description: 'Build automated continuous integration pipelines, infrastructure as code, container orchestration, and observability platforms.',
    icon: 'Terminal',
    skills: ['Kubernetes Orchestration', 'Infrastructure as Code', 'eBPF Observability', 'CI/CD Pipelines', 'Cloud Security'],
    technologies: ['Kubernetes', 'Terraform', 'Docker', 'AWS / GCP', 'eBPF'],
    averageSalary: '$140,000 - $210,000',
    growthRate: 35,
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity & Application Security',
    description: 'Protect enterprise infrastructure, analyze vulnerabilities, implement zero-trust architectures, and secure supply chains.',
    icon: 'Shield',
    skills: ['Threat Modeling', 'Zero Trust Architecture', 'Penetration Testing', 'Cryptography', 'Memory Safety Auditing'],
    technologies: ['Rust', 'eBPF', 'Wazuh', 'HashiCorp Vault', 'WireGuard'],
    averageSalary: '$145,000 - $220,000',
    growthRate: 40,
  },
  {
    id: 'data-science',
    name: 'Data Science & Analytics',
    description: 'Extract statistical insights, build predictive models, design experiment frameworks, and build data lakes.',
    icon: 'BarChart3',
    skills: ['Exploratory Data Analysis', 'Statistical Modeling', 'Feature Engineering', 'Data Warehousing', 'BI Visualization'],
    technologies: ['Python', 'DuckDB', 'Apache Spark', 'Polars', 'dbt'],
    averageSalary: '$130,000 - $190,000',
    growthRate: 26,
  },
];
