import type { Source, StoryCluster, ProcessingJob, AdminStats } from '../types';
import { articles, sources as initialSources, sourcesMap } from './articles';

export const sourcesList: Source[] = [
  ...initialSources,
  { id: 'aws-architecture', name: 'AWS Architecture Blog', url: 'https://aws.amazon.com/blogs/architecture', type: 'Official Blog', category: 'Cloud', trustScore: 10, status: 'active', articlesCount: 890, lastChecked: '2026-09-23T08:30:00Z', collectionFrequency: '4 hours' },
  { id: 'acm-digital', name: 'ACM Digital Library', url: 'https://dl.acm.org', type: 'Research', category: 'Research', trustScore: 10, status: 'active', articlesCount: 15400, lastChecked: '2026-09-23T06:00:00Z', collectionFrequency: '24 hours' },
  { id: 'ieee-xplore', name: 'IEEE Xplore', url: 'https://ieeexplore.ieee.org', type: 'Research', category: 'Research', trustScore: 10, status: 'active', articlesCount: 22100, lastChecked: '2026-09-23T06:30:00Z', collectionFrequency: '24 hours' },
  { id: 'cloudflare-blog', name: 'Cloudflare Tech Blog', url: 'https://blog.cloudflare.com', type: 'Official Blog', category: 'Cybersecurity', trustScore: 10, status: 'active', articlesCount: 680, lastChecked: '2026-09-23T09:50:00Z', collectionFrequency: '6 hours' },
];

export const storyClusters: StoryCluster[] = [
  {
    id: 'cluster-claude35',
    title: 'Anthropic Introduces Computer Use and Upgraded Claude 3.5 Sonnet',
    summary: 'Anthropic officially launched Computer Use in public beta alongside an upgraded Claude 3.5 Sonnet, empowering AI agents to interact with desktop screens, move cursors, type, and automate multi-application workflows.',
    articleCount: 18,
    sourceCount: 5,
    publishedAt: '2024-10-22T14:00:00Z',
    technologies: ['LLM Agents', 'Computer Use', 'Autonomous AI'],
    category: 'AI/ML',
    primarySource: sourcesMap['anthropic-news'],
    articles: [
      {
        id: 'c35-art-1',
        title: 'Introducing Computer Use: A New Way for Claude 3.5 Sonnet to Interact with Computers',
        summary: 'Anthropic officially launches computer use in public beta, introducing state-of-the-art agentic reasoning and direct desktop software execution.',
        url: 'https://www.anthropic.com/news/3-5-models-and-computer-use',
        imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80',
        source: sourcesMap['anthropic-news'],
        publishedAt: '2024-10-22T14:00:00Z',
        category: 'AI/ML',
        technologies: ['LLM Agents', 'Computer Use', 'AI'],
        readingTime: 6,
        clusterSize: 18,
        clusterId: 'cluster-claude35',
      },
      {
        id: 'c35-art-2',
        title: 'Anthropic Quickstarts: Autonomous Computer Use Agent Reference Architecture',
        summary: 'Open-source reference implementation and containerized demo for deploying Claude 3.5 Sonnet computer-use agent workflows.',
        url: 'https://github.com/anthropics/anthropic-quickstarts/tree/main/computer-use-demo',
        imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80',
        source: sourcesMap['github-blog'],
        publishedAt: '2024-10-22T14:30:00Z',
        category: 'Developer Tools',
        technologies: ['LLM Agents', 'Docker', 'Automation'],
        readingTime: 8,
        clusterSize: 18,
        clusterId: 'cluster-claude35',
      },
      {
        id: 'c35-art-3',
        title: 'Claude 3.5 Sonnet Architecture, Benchmarks, and Model Card',
        summary: 'Detailed evaluation of Claude 3.5 Sonnet on SWE-bench verified tasks, vision reasoning, and instruction-following benchmarks.',
        url: 'https://www.anthropic.com/news/claude-3-5-sonnet',
        imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
        source: sourcesMap['anthropic-news'],
        publishedAt: '2024-10-22T15:00:00Z',
        category: 'AI/ML',
        technologies: ['LLM Agents', 'Benchmarks', 'Computer Vision'],
        readingTime: 7,
        clusterSize: 18,
        clusterId: 'cluster-claude35',
      },
      {
        id: 'c35-art-4',
        title: 'MIT Technology Review: AI Agents and Autonomous Desktop Task Synthesis',
        summary: 'Analysis of how Anthropic\'s computer use capabilities shift the evaluation frontier from passive chat toward active OS automation.',
        url: 'https://www.technologyreview.com/topic/artificial-intelligence/',
        imageUrl: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=600&q=80',
        source: sourcesMap['mit-tech-review'],
        publishedAt: '2024-10-22T16:00:00Z',
        category: 'AI/ML',
        technologies: ['Autonomous AI', 'Emerging Tech'],
        readingTime: 9,
        clusterSize: 18,
        clusterId: 'cluster-claude35',
      },
      {
        id: 'c35-art-5',
        title: 'Discussion: Claude 3.5 Sonnet and Computer Use Public Beta',
        summary: 'Developer community reactions, latency benchmarks, container setup guides, and prompt strategies for Claude computer use.',
        url: 'https://news.ycombinator.com/item?id=41914948',
        imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
        source: sourcesMap['hn'],
        publishedAt: '2024-10-22T17:00:00Z',
        category: 'AI/ML',
        technologies: ['LLM Agents', 'Developer Tools'],
        readingTime: 5,
        clusterSize: 18,
        clusterId: 'cluster-claude35',
      },
    ],
  },
  {
    id: 'cluster-rust-linux',
    title: 'Linux Kernel Mainline Integrates Production Rust Infrastructure',
    summary: 'Linus Torvalds and subsystem maintainers merged native Rust abstraction layers and device drivers into the mainline tree, addressing historical memory vulnerability vectors with zero-cost safety guarantees.',
    articleCount: 15,
    sourceCount: 5,
    publishedAt: '2024-09-18T10:30:00Z',
    technologies: ['Rust', 'Linux', 'Systems Programming'],
    category: 'Languages',
    primarySource: { id: 'linux-kernel', name: 'Kernel.org Documentation', url: 'https://docs.kernel.org/rust/index.html', type: 'Official Documentation', category: 'Systems', trustScore: 10, status: 'active', articlesCount: 120, lastChecked: new Date().toISOString(), collectionFrequency: '24 hours' },
    articles: [
      {
        id: 'rl-art-1',
        title: 'The Linux Kernel Rust Infrastructure and Subsystem Documentation',
        summary: 'Official documentation and guidelines for compiling and developing device drivers using Rust abstractions in mainline Linux.',
        url: 'https://docs.kernel.org/rust/index.html',
        imageUrl: 'https://images.unsplash.com/photo-1629654291663-b91ad427698f?w=600&q=80',
        source: { id: 'linux-kernel', name: 'Kernel.org Documentation', url: 'https://docs.kernel.org/rust/index.html', type: 'Official Documentation', category: 'Systems', trustScore: 10, status: 'active', articlesCount: 120, lastChecked: new Date().toISOString(), collectionFrequency: '24 hours' },
        publishedAt: '2024-09-18T10:30:00Z',
        category: 'Languages',
        technologies: ['Rust', 'Linux', 'Systems Programming'],
        readingTime: 12,
        clusterSize: 15,
        clusterId: 'cluster-rust-linux',
      },
      {
        id: 'rl-art-2',
        title: 'Rust for Linux: Memory Safety in the Linux Kernel Tree',
        summary: 'The official Rust for Linux project portal outlining subsystem bindings, driver modules, and architecture support.',
        url: 'https://rust-for-linux.com/',
        imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80',
        source: { id: 'rust-for-linux', name: 'Rust for Linux Project', url: 'https://rust-for-linux.com', type: 'Official Project', category: 'Systems', trustScore: 10, status: 'active', articlesCount: 80, lastChecked: new Date().toISOString(), collectionFrequency: '24 hours' },
        publishedAt: '2024-09-18T11:00:00Z',
        category: 'Systems',
        technologies: ['Rust', 'Linux', 'Memory Safety'],
        readingTime: 6,
        clusterSize: 15,
        clusterId: 'cluster-rust-linux',
      },
      {
        id: 'rl-art-3',
        title: 'Rust abstractions in the 6.1 kernel: Memory safety guarantees and mainline merge',
        summary: 'LWN.net provides an in-depth technical analysis of memory safety verification and safe C-FFI bindings in mainline drivers.',
        url: 'https://lwn.net/Articles/910762/',
        imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80',
        source: sourcesMap['lwn-net'],
        publishedAt: '2024-09-18T12:00:00Z',
        category: 'Systems',
        technologies: ['Rust', 'Linux', 'Security'],
        readingTime: 14,
        clusterSize: 15,
        clusterId: 'cluster-rust-linux',
      },
      {
        id: 'rl-art-4',
        title: 'Rust-for-Linux Linux Kernel Source Tree and Device Drivers',
        summary: 'GitHub repository for the Rust for Linux integration branch containing sample modules and architecture bindings.',
        url: 'https://github.com/Rust-for-Linux/linux',
        imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
        source: sourcesMap['github-blog'],
        publishedAt: '2024-09-18T14:00:00Z',
        category: 'Developer Tools',
        technologies: ['Rust', 'Linux', 'Open Source'],
        readingTime: 5,
        clusterSize: 15,
        clusterId: 'cluster-rust-linux',
      },
      {
        id: 'rl-art-5',
        title: 'Discussion: Rust Merged into Linux 6.1 Mainline Tree',
        summary: 'Hacker News community analyzes Linus Torvalds merging the initial Rust infrastructure into the mainline tree.',
        url: 'https://news.ycombinator.com/item?id=33074395',
        imageUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&q=80',
        source: sourcesMap['hn'],
        publishedAt: '2024-09-18T16:00:00Z',
        category: 'Languages',
        technologies: ['Rust', 'Linux'],
        readingTime: 5,
        clusterSize: 15,
        clusterId: 'cluster-rust-linux',
      },
    ],
  },
  {
    id: 'cluster-quantum-error',
    title: 'Harvard and QuEra Demonstrate Fault-Tolerant Logical Qubits in Nature',
    summary: 'Researchers demonstrate a neutral-atom quantum processor operating with 48 logical qubits and topological error mitigation, bringing fault-tolerant logical compute steps closer to practical reality.',
    articleCount: 12,
    sourceCount: 5,
    publishedAt: '2024-08-30T16:00:00Z',
    technologies: ['Quantum Computing', 'Neutral Atoms', 'Logical Qubits'],
    category: 'Quantum',
    primarySource: sourcesMap['nature-physics'],
    articles: [
      {
        id: 'qe-art-1',
        title: 'A quantum processor based on coherent transport of entangled atom arrays',
        summary: 'Peer-reviewed research paper in Nature demonstrating fault-tolerant logical algorithms executed on neutral atom arrays.',
        url: 'https://www.nature.com/articles/s41586-023-06927-3',
        imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80',
        source: sourcesMap['nature-physics'],
        publishedAt: '2024-08-30T16:00:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing', 'Physics'],
        readingTime: 15,
        clusterSize: 12,
        clusterId: 'cluster-quantum-error',
      },
      {
        id: 'qe-art-2',
        title: 'Harvard-led team demonstrates first quantum computer with logical qubits',
        summary: 'Harvard Gazette report on the realization of 48 dual-rail logical qubits capable of detecting and correcting computational errors.',
        url: 'https://news.harvard.edu/gazette/story/2023/12/harvard-led-team-creates-first-quantum-computer-with-logical-qubits/',
        imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=600&q=80',
        source: { id: 'harvard', name: 'Harvard Gazette', url: 'https://news.harvard.edu', type: 'University Press', category: 'Quantum', trustScore: 10, status: 'active', articlesCount: 50, lastChecked: new Date().toISOString(), collectionFrequency: '24 hours' },
        publishedAt: '2024-08-30T17:00:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing', 'Emerging Tech'],
        readingTime: 7,
        clusterSize: 12,
        clusterId: 'cluster-quantum-error',
      },
      {
        id: 'qe-art-3',
        title: 'Logical Quantum Processor with Neutral Atoms and Topological Error Mitigation',
        summary: 'Full arXiv preprint detailing the cryogenic apparatus, laser tweezer arrays, and syndrome measurement circuits.',
        url: 'https://arxiv.org/abs/2312.03818',
        imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&q=80',
        source: sourcesMap['arxiv'],
        publishedAt: '2024-08-30T18:00:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing', 'Research'],
        readingTime: 12,
        clusterSize: 12,
        clusterId: 'cluster-quantum-error',
      },
      {
        id: 'qe-art-4',
        title: 'QuEra Announces Architecture for Fault-Tolerant Quantum Scalability',
        summary: 'Commercial roadmap and system specifications for scalable neutral-atom quantum processors with active error correction.',
        url: 'https://www.quera.com/press-releases/first-logical-quantum-processor',
        imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&q=80',
        source: { id: 'quera', name: 'QuEra Computing', url: 'https://www.quera.com', type: 'Official Blog', category: 'Quantum', trustScore: 9, status: 'active', articlesCount: 30, lastChecked: new Date().toISOString(), collectionFrequency: '24 hours' },
        publishedAt: '2024-08-30T19:00:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing', 'Hardware'],
        readingTime: 6,
        clusterSize: 12,
        clusterId: 'cluster-quantum-error',
      },
      {
        id: 'qe-art-5',
        title: 'Discussion: First Quantum Computer with 48 Logical Qubits Demonstrated',
        summary: 'Physicists and quantum software developers analyze the fault-tolerant error threshold on Hacker News.',
        url: 'https://news.ycombinator.com/item?id=38546594',
        imageUrl: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=600&q=80',
        source: sourcesMap['hn'],
        publishedAt: '2024-08-30T20:00:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing'],
        readingTime: 5,
        clusterSize: 12,
        clusterId: 'cluster-quantum-error',
      },
    ],
  },
  {
    id: 'cluster-openai-o1',
    title: 'OpenAI Releases o1 Reasoning Model with Inference-Time Compute',
    summary: 'OpenAI unveiled the o1 reasoning series, using reinforcement learning and chain-of-thought to solve complex competitive math, science, and coding challenges.',
    articleCount: 16,
    sourceCount: 4,
    publishedAt: '2024-09-12T17:00:00Z',
    technologies: ['LLM Reasoning', 'Chain of Thought', 'RL'],
    category: 'AI/ML',
    primarySource: sourcesMap['openai-blog'],
    articles: [
      {
        id: 'o1-art-1',
        title: 'Learning to Reason with LLMs: Introducing OpenAI o1-preview and o1-mini',
        summary: 'OpenAI officially announces o1, training models to produce private reasoning chains before formulating final responses.',
        url: 'https://openai.com/index/introducing-openai-o1-preview/',
        imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
        source: sourcesMap['openai-blog'],
        publishedAt: '2024-09-12T17:00:00Z',
        category: 'AI/ML',
        technologies: ['LLM Reasoning', 'AI'],
        readingTime: 8,
        clusterSize: 16,
        clusterId: 'cluster-openai-o1',
      },
      {
        id: 'o1-art-2',
        title: 'OpenAI Research: Frontier Model Safety Evaluation and Reasoning',
        summary: 'Safety evaluations demonstrate how chain-of-thought allows models to adhere to safety guidelines and resist jailbreaks.',
        url: 'https://openai.com/research',
        imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&q=80',
        source: sourcesMap['openai-blog'],
        publishedAt: '2024-09-12T17:30:00Z',
        category: 'AI/ML',
        technologies: ['AI Safety', 'Alignment'],
        readingTime: 9,
        clusterSize: 16,
        clusterId: 'cluster-openai-o1',
      },
      {
        id: 'o1-art-3',
        title: 'MIT Technology Review: AI Models That Think Before They Speak',
        summary: 'Deep dive into inference-time compute scaling and how o1 compares to traditional pre-trained autoregressive models.',
        url: 'https://www.technologyreview.com/topic/artificial-intelligence/',
        imageUrl: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=600&q=80',
        source: sourcesMap['mit-tech-review'],
        publishedAt: '2024-09-12T18:00:00Z',
        category: 'AI/ML',
        technologies: ['Inference Compute', 'Emerging Tech'],
        readingTime: 6,
        clusterSize: 16,
        clusterId: 'cluster-openai-o1',
      },
      {
        id: 'o1-art-4',
        title: 'Discussion: OpenAI o1 Reasoning Architecture and Benchmarks',
        summary: 'Developer breakdown of SWE-bench verified scores, AIME competitive math performance, and token pricing.',
        url: 'https://news.ycombinator.com/item?id=41521797',
        imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
        source: sourcesMap['hn'],
        publishedAt: '2024-09-12T18:30:00Z',
        category: 'AI/ML',
        technologies: ['LLM Reasoning', 'Developer Tools'],
        readingTime: 5,
        clusterSize: 16,
        clusterId: 'cluster-openai-o1',
      },
    ],
  },
];

export const processingJobs: ProcessingJob[] = [
  {
    id: 'job-1',
    name: 'RSS Feed Ingestion Pipeline',
    status: 'running',
    lastRun: '2026-09-23T11:20:00Z',
    nextRun: '2026-09-23T11:35:00Z',
    processedCount: 1248,
    errorCount: 2,
    details: 'Polling 42 active RSS feeds across global tech portals',
  },
  {
    id: 'job-2',
    name: 'AI Entity & Technology Extraction',
    status: 'running',
    lastRun: '2026-09-23T11:22:00Z',
    nextRun: '2026-09-23T11:25:00Z',
    processedCount: 854,
    errorCount: 0,
    details: 'FastAPI NLP service tagger: identifying emerging tech tokens',
  },
  {
    id: 'job-3',
    name: 'Story Clustering & Deduplication',
    status: 'completed',
    lastRun: '2026-09-23T11:15:00Z',
    nextRun: '2026-09-23T11:45:00Z',
    processedCount: 186,
    errorCount: 0,
    details: 'Semantic similarity threshold > 0.88 grouped into clusters',
  },
  {
    id: 'job-4',
    name: 'Trend Velocity & Scoring Engine',
    status: 'completed',
    lastRun: '2026-09-23T11:00:00Z',
    nextRun: '2026-09-23T12:00:00Z',
    processedCount: 1876,
    errorCount: 0,
    details: 'Updated mentions, source diversity, and 7-day sparklines',
  },
  {
    id: 'job-5',
    name: 'Personalized Newsletter Compiler',
    status: 'queued',
    lastRun: '2026-09-23T06:00:00Z',
    nextRun: '2026-09-24T06:00:00Z',
    processedCount: 14250,
    errorCount: 1,
    details: 'Compiling personalized daily digest for 14.2k active subscribers',
  },
];

export const adminStats: AdminStats = {
  totalUsers: 24890,
  activeUsers: 14250,
  articlesCollected: 184520,
  sourcesCount: 342,
  technologiesCount: 1876,
  emergingTrends: 17,
  emailsSent: 684200,
  processingFailures: 7,
};
