import type { Source, StoryCluster, ProcessingJob, AdminStats } from '../types';
import { articles, sources as initialSources, sourcesMap } from './articles';

export const sourcesList: Source[] = [
  ...initialSources,
  { id: 'aws-architecture', name: 'AWS Architecture Blog', url: 'https://aws.amazon.com/blogs/architecture', type: 'Official Blog', category: 'Cloud', trustScore: 10, status: 'active', articlesCount: 890, lastChecked: '2026-09-23T08:30:00Z', collectionFrequency: '4 hours' },
  { id: 'acm-digital', name: 'ACM Digital Library', url: 'https://dl.acm.org', type: 'Research', category: 'Research', trustScore: 10, status: 'active', articlesCount: 15400, lastChecked: '2026-09-23T06:00:00Z', collectionFrequency: '24 hours' },
  { id: 'ieee-xplore', name: 'IEEE Xplore', url: 'https://ieeexplore.ieee.org', type: 'Research', category: 'Research', trustScore: 10, status: 'active', articlesCount: 22100, lastChecked: '2026-09-23T06:30:00Z', collectionFrequency: '24 hours' },
  { id: 'cloudflare-blog', name: 'Cloudflare Tech Blog', url: 'https://blog.cloudflare.com', type: 'Official Blog', category: 'Cybersecurity', trustScore: 10, status: 'active', articlesCount: 680, lastChecked: '2026-09-23T09:50:00Z', collectionFrequency: '6 hours' },
];

export const storyClusters: StoryCluster[] = [
  {
    id: 'cluster-claude4',
    title: 'Anthropic Announces Next-Gen Frontier Models with Autonomous Agent Capabilities',
    summary: 'Multiple tier-1 outlets and research entities reported on the Claude 4 architecture release, highlighting benchmark supremacy in software synthesis, multi-modal reasoning, and extended memory execution.',
    articleCount: 14,
    sourceCount: 6,
    publishedAt: '2026-09-23T08:00:00Z',
    technologies: ['LLM Agents', 'RAG', 'Transformer Architecture'],
    category: 'AI/ML',
    primarySource: sourcesMap['anthropic-news'],
    articles: [
      {
        id: 'c4-art-1',
        title: 'Anthropic Releases Claude 4 with 200K Context and Enhanced Reasoning',
        summary: 'Anthropic\'s latest Claude 4 model introduces a 200,000 token context window, dramatically improved reasoning capabilities, and new tool use features that enable complex multi-step agent workflows.',
        url: 'https://anthropic.com/news/claude-4',
        imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80',
        source: sourcesMap['anthropic-news'],
        publishedAt: '2026-09-23T08:00:00Z',
        category: 'AI/ML',
        technologies: ['LLM Agents', 'RAG', 'Transformer Architecture'],
        readingTime: 8,
        clusterSize: 14,
        clusterId: 'cluster-claude4',
      },
      {
        id: 'c4-art-2',
        title: 'Anthropic\'s Claude 4 targets enterprise workflows with autonomous agent execution',
        summary: 'TechCrunch examines Claude 4\'s benchmark results in software engineering, multi-turn reasoning, and enterprise compliance.',
        url: 'https://techcrunch.com/2026/09/23/anthropic-claude-4-agents',
        imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
        source: sourcesMap['techcrunch'],
        publishedAt: '2026-09-23T08:45:00Z',
        category: 'AI/ML',
        technologies: ['LLM Agents', 'AI', 'Enterprise Software'],
        readingTime: 6,
        clusterSize: 14,
        clusterId: 'cluster-claude4',
      },
      {
        id: 'c4-art-3',
        title: 'Claude 4 debuts: How Anthropic plans to challenge frontier AI reasoning benchmarks',
        summary: 'The Verge analyzes the new architecture, benchmark leaps in software engineering, and safety guardrails in Claude 4.',
        url: 'https://theverge.com/2026/09/23/anthropic-claude-4-frontier-model',
        imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&q=80',
        source: sourcesMap['the-verge'],
        publishedAt: '2026-09-23T09:15:00Z',
        category: 'AI/ML',
        technologies: ['LLM Agents', 'Transformer Architecture', 'Benchmarks'],
        readingTime: 7,
        clusterSize: 14,
        clusterId: 'cluster-claude4',
      },
      {
        id: 'c4-art-4',
        title: 'Why Anthropic\'s Claude 4 focus on agentic autonomy marks a shift in frontier AI',
        summary: 'MIT Technology Review takes a deep dive into Claude 4\'s persistent state execution and automated task synthesis.',
        url: 'https://technologyreview.com/2026/09/23/claude-4-agentic-shift',
        imageUrl: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=600&q=80',
        source: sourcesMap['mit-tech-review'],
        publishedAt: '2026-09-23T09:50:00Z',
        category: 'AI/ML',
        technologies: ['LLM Agents', 'AI Safety', 'Emerging Tech'],
        readingTime: 9,
        clusterSize: 14,
        clusterId: 'cluster-claude4',
      },
      {
        id: 'c4-art-5',
        title: 'Claude 4 Architecture: 200K Context Window, Tool APIs, and Agent Protocols',
        summary: 'InfoQ architectural breakdown of the new tool use protocols and agentic loop orchestration introduced with Claude 4.',
        url: 'https://infoq.com/news/2026/09/anthropic-claude-4-architecture',
        imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80',
        source: sourcesMap['infoq'],
        publishedAt: '2026-09-23T10:30:00Z',
        category: 'AI/ML',
        technologies: ['LLM Agents', 'RAG', 'Software Engineering'],
        readingTime: 10,
        clusterSize: 14,
        clusterId: 'cluster-claude4',
      },
      {
        id: 'c4-art-6',
        title: 'Discussion: Claude 4 System Prompts, Agent Tool APIs, and Early Benchmarks',
        summary: 'Hacker News developer discussions, latency measurements, and prompt engineering discoveries from early Claude 4 access.',
        url: 'https://news.ycombinator.com/item?id=41628104',
        imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
        source: sourcesMap['hn'],
        publishedAt: '2026-09-23T11:00:00Z',
        category: 'AI/ML',
        technologies: ['LLM Agents', 'Developer Tools'],
        readingTime: 5,
        clusterSize: 14,
        clusterId: 'cluster-claude4',
      },
    ],
  },
  {
    id: 'cluster-rust-linux',
    title: 'Linux Kernel Integrates Rust Production Drivers Across Mainline Subsystems',
    summary: 'Torvalds and subsystem maintainers merged native Rust abstraction layers and zero-cost safety drivers into the mainline tree, addressing historical memory vulnerability vectors.',
    articleCount: 18,
    sourceCount: 5,
    publishedAt: '2026-09-22T14:30:00Z',
    technologies: ['Rust', 'Linux', 'Systems Programming'],
    category: 'Languages',
    primarySource: sourcesMap['rust-blog'],
    articles: [
      {
        id: 'rl-art-1',
        title: 'Rust Joins the Linux Kernel: Production Drivers Now Available',
        summary: 'The Linux kernel has officially merged its first batch of production-ready Rust drivers, marking a historic milestone in systems programming and memory-safe OS development.',
        url: 'https://blog.rust-lang.org/linux-kernel',
        imageUrl: 'https://images.unsplash.com/photo-1629654291663-b91ad427698f?w=600&q=80',
        source: sourcesMap['rust-blog'],
        publishedAt: '2026-09-22T14:30:00Z',
        category: 'Languages',
        technologies: ['Rust', 'Linux', 'Systems Programming'],
        readingTime: 12,
        clusterSize: 18,
        clusterId: 'cluster-rust-linux',
      },
      {
        id: 'rl-art-2',
        title: 'Torvalds merges production-ready Rust drivers into mainline Linux kernel tree',
        summary: 'The Register reports on Linus Torvalds merging the latest Rust infrastructure and NVMe drivers into the mainline kernel tree.',
        url: 'https://theregister.com/2026/09/22/linux_kernel_rust_production',
        imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80',
        source: sourcesMap['the-register'],
        publishedAt: '2026-09-22T15:15:00Z',
        category: 'Languages',
        technologies: ['Linux', 'Rust', 'Systems Programming'],
        readingTime: 6,
        clusterSize: 18,
        clusterId: 'cluster-rust-linux',
      },
      {
        id: 'rl-art-3',
        title: 'Rust abstractions in the 6.x kernel: memory safety guarantees and subsystem audit',
        summary: 'LWN.net provides an in-depth technical analysis of memory safety verification and safe C-FFI bindings in mainline drivers.',
        url: 'https://lwn.net/Articles/982341',
        imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80',
        source: sourcesMap['lwn-net'],
        publishedAt: '2026-09-22T16:00:00Z',
        category: 'Systems',
        technologies: ['Rust', 'Linux', 'Security'],
        readingTime: 14,
        clusterSize: 18,
        clusterId: 'cluster-rust-linux',
      },
      {
        id: 'rl-art-4',
        title: 'Production Rust drivers show zero-overhead performance in early Linux I/O benchmarks',
        summary: 'Phoronix runs comprehensive benchmark suites showing native throughput parity between legacy C modules and new Rust drivers.',
        url: 'https://phoronix.com/news/linux-rust-drivers-benchmarks',
        imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
        source: sourcesMap['phoronix'],
        publishedAt: '2026-09-22T16:45:00Z',
        category: 'Systems',
        technologies: ['Rust', 'Linux', 'Benchmarks'],
        readingTime: 8,
        clusterSize: 18,
        clusterId: 'cluster-rust-linux',
      },
      {
        id: 'rl-art-5',
        title: 'Discussion: Linux Kernel Mainline Officially Merges Production Rust Drivers',
        summary: 'Hacker News developers debate the ergonomics, compiler toolchain requirements, and future of driver development in Rust.',
        url: 'https://news.ycombinator.com/item?id=41620194',
        imageUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&q=80',
        source: sourcesMap['hn'],
        publishedAt: '2026-09-22T17:30:00Z',
        category: 'Languages',
        technologies: ['Rust', 'Linux'],
        readingTime: 5,
        clusterSize: 18,
        clusterId: 'cluster-rust-linux',
      },
    ],
  },
  {
    id: 'cluster-quantum-error',
    title: 'Breakthrough in Topological Surface Code Syndrome Decoding Latency',
    summary: 'Researchers demonstrate sub-microsecond quantum error mitigation at 99.9% physical gate fidelities, bringing fault-tolerant logical compute steps closer to practical reality.',
    articleCount: 8,
    sourceCount: 5,
    publishedAt: '2026-09-21T18:00:00Z',
    technologies: ['Quantum Computing', 'Qiskit'],
    category: 'Quantum',
    primarySource: sourcesMap['nature-physics'],
    articles: [
      {
        id: 'qe-art-1',
        title: 'Sub-microsecond fault-tolerant quantum error correction in superconducting circuits',
        summary: 'Experimental demonstration of real-time syndrome extraction and sub-microsecond decoding across topological surface codes.',
        url: 'https://nature.com/articles/s41567-026-02401-x',
        imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80',
        source: sourcesMap['nature-physics'],
        publishedAt: '2026-09-21T18:00:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing', 'Physics'],
        readingTime: 15,
        clusterSize: 8,
        clusterId: 'cluster-quantum-error',
      },
      {
        id: 'qe-art-2',
        title: 'Real-time syndrome decoding on topological surface codes under 1 microsecond latency',
        summary: 'Preprint paper detailing FPGA decoding pipelines that process error syndromes faster than physical qubit coherence decay.',
        url: 'https://arxiv.org/abs/2609.10421',
        imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&q=80',
        source: sourcesMap['arxiv'],
        publishedAt: '2026-09-21T18:45:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing', 'Research'],
        readingTime: 12,
        clusterSize: 8,
        clusterId: 'cluster-quantum-error',
      },
      {
        id: 'qe-art-3',
        title: 'Quantum computing edges closer to fault tolerance with ultra-fast syndrome decoding',
        summary: 'MIT Technology Review explains how sub-microsecond decoding solves the quantum bottleneck to practical logical qubits.',
        url: 'https://technologyreview.com/quantum-surface-code-breakthrough',
        imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=600&q=80',
        source: sourcesMap['mit-tech-review'],
        publishedAt: '2026-09-21T19:30:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing', 'Emerging Tech'],
        readingTime: 7,
        clusterSize: 8,
        clusterId: 'cluster-quantum-error',
      },
      {
        id: 'qe-art-4',
        title: 'Topological surface code decoder clears critical barrier for scalable quantum processors',
        summary: 'IEEE Spectrum dives into cryogenic ASIC architectures that perform syndrome correlation at gigahertz speeds.',
        url: 'https://spectrum.ieee.org/quantum-error-mitigation-syndrome',
        imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&q=80',
        source: sourcesMap['ieee-spectrum'],
        publishedAt: '2026-09-21T20:15:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing', 'Hardware'],
        readingTime: 9,
        clusterSize: 8,
        clusterId: 'cluster-quantum-error',
      },
      {
        id: 'qe-art-5',
        title: 'Show HN / Research: Real-time Topological Quantum Error Correction Benchmark',
        summary: 'Quantum engineers and researchers discuss experimental data and reproducibility on Hacker News.',
        url: 'https://news.ycombinator.com/item?id=41614290',
        imageUrl: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=600&q=80',
        source: sourcesMap['hn'],
        publishedAt: '2026-09-21T21:00:00Z',
        category: 'Quantum',
        technologies: ['Quantum Computing'],
        readingTime: 6,
        clusterSize: 8,
        clusterId: 'cluster-quantum-error',
      },
    ],
  },
];

export const processingJobs: ProcessingJob[] = [
  {
    id: 'job-1',
    name: 'RSS Feed Ingestion Pipeline',
    status: 'running',
    lastRun: '2026-09-23T11:20:00Z',
    nextRun: '2026-09-23T11:35:00Z',
    processedCount: 1248,
    errorCount: 2,
    details: 'Polling 42 active RSS feeds across global tech portals',
  },
  {
    id: 'job-2',
    name: 'AI Entity & Technology Extraction',
    status: 'running',
    lastRun: '2026-09-23T11:22:00Z',
    nextRun: '2026-09-23T11:25:00Z',
    processedCount: 854,
    errorCount: 0,
    details: 'FastAPI NLP service tagger: identifying emerging tech tokens',
  },
  {
    id: 'job-3',
    name: 'Story Clustering & Deduplication',
    status: 'completed',
    lastRun: '2026-09-23T11:15:00Z',
    nextRun: '2026-09-23T11:45:00Z',
    processedCount: 186,
    errorCount: 0,
    details: 'Semantic similarity threshold > 0.88 grouped into clusters',
  },
  {
    id: 'job-4',
    name: 'Trend Velocity & Scoring Engine',
    status: 'completed',
    lastRun: '2026-09-23T11:00:00Z',
    nextRun: '2026-09-23T12:00:00Z',
    processedCount: 1876,
    errorCount: 0,
    details: 'Updated mentions, source diversity, and 7-day sparklines',
  },
  {
    id: 'job-5',
    name: 'Personalized Newsletter Compiler',
    status: 'queued',
    lastRun: '2026-09-23T06:00:00Z',
    nextRun: '2026-09-24T06:00:00Z',
    processedCount: 14250,
    errorCount: 1,
    details: 'Compiling personalized daily digest for 14.2k active subscribers',
  },
];

export const adminStats: AdminStats = {
  totalUsers: 24890,
  activeUsers: 14250,
  articlesCollected: 184520,
  sourcesCount: 342,
  technologiesCount: 1876,
  emergingTrends: 17,
  emailsSent: 684200,
  processingFailures: 7,
};
