import type { Technology, TrendDataPoint } from '../types';

// Generates realistic sparkline data trending upward
function genSparkline(trend: 'up' | 'down' | 'flat' | 'volatile', base: number = 50): number[] {
  const points: number[] = [];
  let val = base;
  for (let i = 0; i < 7; i++) {
    if (trend === 'up') val += Math.random() * 8 - 1;
    else if (trend === 'down') val -= Math.random() * 6 + 1;
    else if (trend === 'flat') val += Math.random() * 4 - 2;
    else val += Math.random() * 20 - 10;
    points.push(Math.max(0, Math.round(val)));
  }
  return points;
}

export const technologies: Technology[] = [
  {
    id: 'llm-agents',
    slug: 'llm-agents',
    name: 'LLM Agents',
    category: 'AI/ML',
    description: 'Autonomous AI agents powered by large language models that can plan, reason, and execute complex tasks with minimal human intervention.',
    trendScore: 96,
    mentions: 412,
    sources: 74,
    growth: 128,
    status: 'trending',
    firstDetected: '2024-01-15',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 30),
    tags: ['AI', 'Agents', 'LLM', 'Automation'],
    relatedTechs: ['openai-gpt4', 'langchain', 'rag'],
    whyTrending: 'LLM Agents are experiencing explosive growth due to breakthroughs in autonomous reasoning, tool use, and multi-agent orchestration. Major enterprises are rapidly adopting agentic AI workflows to automate complex knowledge work.',
    followersCount: 3421,
    website: 'https://openai.com',
  },
  {
    id: 'rust',
    slug: 'rust',
    name: 'Rust',
    category: 'Languages',
    description: 'A systems programming language focused on safety, speed, and concurrency. Increasingly adopted for OS kernels, WebAssembly, and cloud-native infrastructure.',
    trendScore: 88,
    mentions: 124,
    sources: 38,
    growth: 31,
    status: 'rising',
    firstDetected: '2021-06-10',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 55),
    tags: ['Systems', 'Memory-Safety', 'WebAssembly', 'Performance'],
    relatedTechs: ['webassembly', 'cargo', 'tauri'],
    whyTrending: 'Rust has experienced increased attention due to growing adoption in systems programming, cloud infrastructure, security-focused software development, and Linux kernel contributions. The language\'s memory safety guarantees are attracting enterprise investment.',
    followersCount: 2847,
    website: 'https://www.rust-lang.org',
    github: 'https://github.com/rust-lang/rust',
  },
  {
    id: 'nextjs',
    slug: 'nextjs',
    name: 'Next.js',
    category: 'Frameworks',
    description: 'The leading React framework for production applications with server components, App Router, and seamless full-stack capabilities.',
    trendScore: 85,
    mentions: 198,
    sources: 52,
    growth: 23,
    status: 'trending',
    firstDetected: '2020-10-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 62),
    tags: ['React', 'SSR', 'Full-Stack', 'TypeScript'],
    relatedTechs: ['react', 'typescript', 'vercel'],
    whyTrending: 'Next.js continues to dominate the React ecosystem with its App Router, server components, and seamless deployment on Vercel. Version 15 introduced significant performance improvements.',
    followersCount: 4129,
    website: 'https://nextjs.org',
    github: 'https://github.com/vercel/next.js',
  },
  {
    id: 'react',
    slug: 'react',
    name: 'React',
    category: 'Frameworks',
    description: 'The most widely used JavaScript library for building user interfaces with a component-based architecture.',
    trendScore: 82,
    mentions: 287,
    sources: 61,
    growth: 14,
    status: 'stable',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('flat', 75),
    tags: ['UI', 'Components', 'JavaScript', 'SPA'],
    relatedTechs: ['nextjs', 'typescript', 'react-native'],
    followersCount: 5892,
    website: 'https://react.dev',
    github: 'https://github.com/facebook/react',
  },
  {
    id: 'postgresql',
    slug: 'postgresql',
    name: 'PostgreSQL',
    category: 'Databases',
    description: 'The world\'s most advanced open-source relational database, now with vector search capabilities via pgvector.',
    trendScore: 79,
    mentions: 156,
    sources: 44,
    growth: 8,
    status: 'stable',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('flat', 68),
    tags: ['Database', 'SQL', 'Open Source', 'ACID'],
    relatedTechs: ['pgvector', 'prisma', 'supabase'],
    followersCount: 2341,
    website: 'https://www.postgresql.org',
  },
  {
    id: 'webassembly',
    slug: 'webassembly',
    name: 'WebAssembly',
    category: 'Languages',
    description: 'A binary instruction format enabling near-native performance in browsers and server-side environments.',
    trendScore: 77,
    mentions: 89,
    sources: 29,
    growth: 41,
    status: 'rising',
    firstDetected: '2021-03-15',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 38),
    tags: ['Performance', 'Browser', 'Rust', 'WASM'],
    relatedTechs: ['rust', 'emscripten', 'wasi'],
    followersCount: 1876,
  },
  {
    id: 'pgvector',
    slug: 'pgvector',
    name: 'pgvector',
    category: 'Databases',
    description: 'Open-source vector similarity search for PostgreSQL, enabling AI-powered semantic search directly in your existing database.',
    trendScore: 91,
    mentions: 203,
    sources: 47,
    growth: 87,
    status: 'emerging',
    firstDetected: '2023-11-20',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 15),
    tags: ['Vector DB', 'Semantic Search', 'AI', 'PostgreSQL'],
    relatedTechs: ['postgresql', 'openai-gpt4', 'rag'],
    whyTrending: 'pgvector is surging as teams seek to add AI-powered semantic search to existing PostgreSQL databases without migrating to specialized vector databases.',
    followersCount: 2103,
    github: 'https://github.com/pgvector/pgvector',
  },
  {
    id: 'kubernetes',
    slug: 'kubernetes',
    name: 'Kubernetes',
    category: 'DevOps',
    description: 'The de-facto standard for container orchestration at scale, managing deployment, scaling, and operations of containerized applications.',
    trendScore: 76,
    mentions: 134,
    sources: 39,
    growth: 5,
    status: 'stable',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('flat', 72),
    tags: ['Containers', 'Orchestration', 'Cloud-Native', 'CNCF'],
    relatedTechs: ['docker', 'helm', 'istio'],
    followersCount: 3201,
    website: 'https://kubernetes.io',
  },
  {
    id: 'typescript',
    slug: 'typescript',
    name: 'TypeScript',
    category: 'Languages',
    description: 'Strongly typed programming language that builds on JavaScript, adding static type definitions for better developer experience and code reliability.',
    trendScore: 84,
    mentions: 267,
    sources: 58,
    growth: 19,
    status: 'trending',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 65),
    tags: ['JavaScript', 'Static Typing', 'Developer Experience'],
    relatedTechs: ['react', 'nextjs', 'nodejs'],
    followersCount: 4567,
    website: 'https://www.typescriptlang.org',
  },
  {
    id: 'langchain',
    slug: 'langchain',
    name: 'LangChain',
    category: 'AI/ML',
    description: 'Framework for developing applications powered by large language models, with tools for chaining, memory, and agent capabilities.',
    trendScore: 89,
    mentions: 178,
    sources: 43,
    growth: 64,
    status: 'trending',
    firstDetected: '2023-02-10',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 25),
    tags: ['LLM', 'AI Framework', 'RAG', 'Agents'],
    relatedTechs: ['llm-agents', 'openai-gpt4', 'pgvector'],
    followersCount: 2987,
    github: 'https://github.com/langchain-ai/langchain',
  },
  {
    id: 'rag',
    slug: 'rag',
    name: 'RAG',
    category: 'AI/ML',
    description: 'Retrieval-Augmented Generation — a technique combining information retrieval with LLMs to ground AI responses in factual, current data.',
    trendScore: 93,
    mentions: 334,
    sources: 67,
    growth: 142,
    status: 'emerging',
    firstDetected: '2023-09-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 10),
    tags: ['AI', 'LLM', 'Search', 'Grounding'],
    relatedTechs: ['pgvector', 'langchain', 'llm-agents'],
    whyTrending: 'RAG has become the dominant architecture for building production AI applications that require factual accuracy and access to private or current data, driving massive adoption across enterprise AI teams.',
    followersCount: 3654,
  },
  {
    id: 'bun',
    slug: 'bun',
    name: 'Bun',
    category: 'Developer Tools',
    description: 'An all-in-one JavaScript runtime, package manager, bundler, and test runner designed for speed — significantly faster than Node.js.',
    trendScore: 83,
    mentions: 145,
    sources: 36,
    growth: 72,
    status: 'rising',
    firstDetected: '2022-09-08',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 28),
    tags: ['JavaScript Runtime', 'Performance', 'Package Manager'],
    relatedTechs: ['nodejs', 'deno', 'typescript'],
    followersCount: 2234,
    website: 'https://bun.sh',
    github: 'https://github.com/oven-sh/bun',
  },
  {
    id: 'htmx',
    slug: 'htmx',
    name: 'HTMX',
    category: 'Frameworks',
    description: 'Lightweight library that gives HTML full AJAX, CSS Transitions, WebSockets and Server Sent Events capabilities directly in HTML.',
    trendScore: 72,
    mentions: 98,
    sources: 27,
    growth: 55,
    status: 'rising',
    firstDetected: '2023-06-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 20),
    tags: ['HTML', 'Hypermedia', 'Simplicity', 'AJAX'],
    relatedTechs: ['golang', 'python', 'ruby-on-rails'],
    followersCount: 1432,
    github: 'https://github.com/bigskysoftware/htmx',
  },
  {
    id: 'tensorflow',
    slug: 'tensorflow',
    name: 'TensorFlow',
    category: 'AI/ML',
    description: 'Google\'s open-source machine learning framework used for production ML models at scale.',
    trendScore: 65,
    mentions: 87,
    sources: 31,
    growth: -3,
    status: 'declining',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 60),
    tags: ['ML', 'Deep Learning', 'Python', 'Google'],
    relatedTechs: ['pytorch', 'keras', 'python'],
    followersCount: 2109,
    website: 'https://tensorflow.org',
  },
  {
    id: 'pytorch',
    slug: 'pytorch',
    name: 'PyTorch',
    category: 'AI/ML',
    description: 'Facebook\'s dynamic deep learning framework, the preferred choice for AI research and increasingly for production ML workloads.',
    trendScore: 80,
    mentions: 167,
    sources: 45,
    growth: 27,
    status: 'rising',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 52),
    tags: ['Deep Learning', 'Research', 'Python', 'Meta'],
    relatedTechs: ['python', 'cuda', 'transformers'],
    followersCount: 3102,
  },
  {
    id: 'docker',
    slug: 'docker',
    name: 'Docker',
    category: 'DevOps',
    description: 'Platform for developing, shipping, and running applications in lightweight containers.',
    trendScore: 74,
    mentions: 112,
    sources: 35,
    growth: 2,
    status: 'stable',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('flat', 70),
    tags: ['Containers', 'DevOps', 'Infrastructure'],
    relatedTechs: ['kubernetes', 'podman', 'helm'],
    followersCount: 3876,
    website: 'https://docker.com',
  },
  {
    id: 'deno',
    slug: 'deno',
    name: 'Deno 2',
    category: 'Developer Tools',
    description: 'A modern, secure runtime for JavaScript and TypeScript, now with npm compatibility and improved Node.js interoperability.',
    trendScore: 71,
    mentions: 76,
    sources: 24,
    growth: 38,
    status: 'rising',
    firstDetected: '2024-09-26',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 30),
    tags: ['JavaScript', 'TypeScript', 'Runtime', 'Security'],
    relatedTechs: ['nodejs', 'bun', 'typescript'],
    followersCount: 1234,
    github: 'https://github.com/denoland/deno',
  },
  {
    id: 'tailwindcss',
    slug: 'tailwindcss',
    name: 'Tailwind CSS',
    category: 'Frameworks',
    description: 'Utility-first CSS framework for rapidly building custom user interfaces.',
    trendScore: 81,
    mentions: 189,
    sources: 49,
    growth: 16,
    status: 'trending',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 62),
    tags: ['CSS', 'Utility-First', 'Design System', 'Rapid Development'],
    relatedTechs: ['react', 'nextjs', 'vite'],
    followersCount: 3987,
    website: 'https://tailwindcss.com',
  },
  {
    id: 'supabase',
    slug: 'supabase',
    name: 'Supabase',
    category: 'Developer Tools',
    description: 'Open-source Firebase alternative providing PostgreSQL database, auth, storage, and real-time subscriptions.',
    trendScore: 85,
    mentions: 167,
    sources: 41,
    growth: 48,
    status: 'rising',
    firstDetected: '2022-01-10',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 40),
    tags: ['BaaS', 'PostgreSQL', 'Auth', 'Realtime'],
    relatedTechs: ['postgresql', 'nextjs', 'prisma'],
    followersCount: 2654,
    website: 'https://supabase.com',
    github: 'https://github.com/supabase/supabase',
  },
  {
    id: 'golang',
    slug: 'golang',
    name: 'Go',
    category: 'Languages',
    description: 'Google\'s compiled language known for simplicity, performance, and excellent concurrency primitives, widely used in cloud infrastructure.',
    trendScore: 78,
    mentions: 143,
    sources: 40,
    growth: 12,
    status: 'stable',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('flat', 66),
    tags: ['Cloud', 'Concurrency', 'Performance', 'Backend'],
    relatedTechs: ['kubernetes', 'docker', 'grpc'],
    followersCount: 2876,
    website: 'https://go.dev',
  },
  {
    id: 'astro',
    slug: 'astro',
    name: 'Astro',
    category: 'Frameworks',
    description: 'Web framework for building content-driven websites with zero JavaScript by default and selective hydration.',
    trendScore: 75,
    mentions: 112,
    sources: 32,
    growth: 44,
    status: 'rising',
    firstDetected: '2022-05-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 35),
    tags: ['Static Sites', 'Performance', 'Islands Architecture'],
    relatedTechs: ['react', 'vue', 'svelte'],
    followersCount: 1765,
    github: 'https://github.com/withastro/astro',
  },
  {
    id: 'graphql',
    slug: 'graphql',
    name: 'GraphQL',
    category: 'Developer Tools',
    description: 'Query language and runtime for APIs offering precise data fetching and strong typing.',
    trendScore: 67,
    mentions: 94,
    sources: 28,
    growth: -6,
    status: 'declining',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 62),
    tags: ['API', 'Query Language', 'Type System'],
    relatedTechs: ['rest', 'trpc', 'apollo'],
    followersCount: 1987,
    website: 'https://graphql.org',
  },
  {
    id: 'tauri',
    slug: 'tauri',
    name: 'Tauri',
    category: 'Frameworks',
    description: 'Framework for building tiny, fast desktop applications using Rust backend and any web frontend.',
    trendScore: 73,
    mentions: 87,
    sources: 25,
    growth: 53,
    status: 'rising',
    firstDetected: '2022-03-15',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 28),
    tags: ['Desktop', 'Rust', 'Cross-platform', 'Performance'],
    relatedTechs: ['rust', 'react', 'typescript'],
    followersCount: 1432,
    github: 'https://github.com/tauri-apps/tauri',
  },
  {
    id: 'zig',
    slug: 'zig',
    name: 'Zig',
    category: 'Languages',
    description: 'General-purpose systems programming language with a focus on robustness, optimality, and clarity — an emerging alternative to C.',
    trendScore: 68,
    mentions: 67,
    sources: 19,
    growth: 76,
    status: 'emerging',
    firstDetected: '2024-05-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('up', 12),
    tags: ['Systems', 'Low-Level', 'Performance', 'C Alternative'],
    relatedTechs: ['rust', 'c', 'bun'],
    whyTrending: 'Zig is gaining significant attention among systems programmers as a modern, safer alternative to C, with unique features like comptime and no hidden control flow.',
    followersCount: 876,
    github: 'https://github.com/ziglang/zig',
  },
  {
    id: 'jquery',
    slug: 'jquery',
    name: 'jQuery',
    category: 'Frameworks',
    description: 'Fast, small, and feature-rich JavaScript DOM manipulation library that dominated early 2010s web development.',
    trendScore: 38,
    mentions: 48,
    sources: 14,
    growth: -42,
    status: 'falling',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 50),
    tags: ['DOM', 'Legacy Web', 'JavaScript'],
    relatedTechs: ['react', 'vue', 'vanilla-js'],
    whyTrending: 'Continuing steep decline as standard browser APIs and declarative reactive frameworks supersede legacy DOM manipulation wrappers.',
    declineReason: 'Native modern Web APIs (fetch, querySelector, ES6+) and reactive frameworks (React, Vue, Svelte) eliminate the need for jQuery.',
    replacedBy: ['React', 'Vue.js', 'Modern Web APIs'],
    followersCount: 1420,
    website: 'https://jquery.com',
    github: 'https://github.com/jquery/jquery',
  },
  {
    id: 'create-react-app',
    slug: 'create-react-app',
    name: 'Create React App',
    category: 'Developer Tools',
    description: 'Officially deprecated single-page app bundler CLI for React originally created by Facebook.',
    trendScore: 24,
    mentions: 21,
    sources: 8,
    growth: -68,
    status: 'falling',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 65),
    tags: ['React', 'Bundler', 'Deprecated', 'Webpack'],
    relatedTechs: ['vite', 'nextjs'],
    whyTrending: 'Officially deprecated in React documentation in favor of Vite, Next.js, and modern ESM tooling.',
    declineReason: 'Official deprecation by React core team due to unmaintained Webpack configurations, slow cold builds, and absence of SSR/RSC capabilities.',
    replacedBy: ['Vite', 'Next.js', 'Remix'],
    followersCount: 890,
    website: 'https://create-react-app.dev',
    github: 'https://github.com/facebook/create-react-app',
  },
  {
    id: 'angularjs-v1',
    slug: 'angularjs-v1',
    name: 'AngularJS (1.x)',
    category: 'Frameworks',
    description: 'Original Model-View-Controller framework for web applications, discontinued by Google.',
    trendScore: 28,
    mentions: 34,
    sources: 9,
    growth: -56,
    status: 'falling',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 55),
    tags: ['MVC', 'Deprecated', 'Frontend'],
    relatedTechs: ['angular', 'react'],
    whyTrending: 'Formal End-of-Life (EOL) passed; enterprise teams are actively completing migrations to modern Angular, React, or Vue.',
    declineReason: 'Official Google EOL, unpatched zero-day vulnerabilities in legacy runtimes, and two-way digest cycle performance bottlenecks.',
    replacedBy: ['Angular (v17+)', 'React', 'Vue 3'],
    followersCount: 1104,
    website: 'https://angularjs.org',
  },
  {
    id: 'objective-c',
    slug: 'objective-c',
    name: 'Objective-C',
    category: 'Languages',
    description: 'General-purpose, object-oriented language historically used for OS X and iOS development before Swift.',
    trendScore: 35,
    mentions: 42,
    sources: 12,
    growth: -46,
    status: 'falling',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 58),
    tags: ['iOS', 'macOS', 'Apple', 'Legacy'],
    relatedTechs: ['swift', 'c++'],
    whyTrending: 'Apple WWDC announcements and modern SDKs are almost exclusively Swift and SwiftUI-first, shrinking legacy Objective-C codebases.',
    declineReason: 'Modern Apple platforms mandate Swift; Objective-C lacks safety features like non-optional pointers, modern concurrency async/await, and SwiftUI ergonomics.',
    replacedBy: ['Swift', 'SwiftUI'],
    followersCount: 1540,
    website: 'https://developer.apple.com/swift',
  },
  {
    id: 'cordova-phonegap',
    slug: 'cordova-phonegap',
    name: 'Apache Cordova / PhoneGap',
    category: 'Mobile',
    description: 'Hybrid mobile app development framework wrapping web apps in native WebView shells.',
    trendScore: 31,
    mentions: 29,
    sources: 7,
    growth: -51,
    status: 'falling',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 52),
    tags: ['Hybrid Mobile', 'WebView', 'Apache'],
    relatedTechs: ['react-native', 'flutter', 'capacitor'],
    whyTrending: 'High latency and poor gesture feel compared to JIT native mobile platforms have led to mass migrations.',
    declineReason: 'Sluggish UI performance in WebViews, poor offline native plugin bridges, and superior developer ergonomics in React Native, Flutter, and Capacitor.',
    replacedBy: ['React Native', 'Flutter', 'Capacitor'],
    followersCount: 975,
    website: 'https://cordova.apache.org',
    github: 'https://github.com/apache/cordova',
  },
  {
    id: 'subversion-svn',
    slug: 'subversion-svn',
    name: 'Apache Subversion (SVN)',
    category: 'Developer Tools',
    description: 'Centralized version control system that preceded the widespread adoption of distributed Git.',
    trendScore: 27,
    mentions: 31,
    sources: 6,
    growth: -59,
    status: 'falling',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 60),
    tags: ['Version Control', 'Centralized', 'Legacy'],
    relatedTechs: ['git'],
    whyTrending: 'Git and cloud repository hosts (GitHub, GitLab) have nearly completely phased out centralized SVN repositories.',
    declineReason: 'Centralized repo single-point-of-failure, painful branching and merging, and lack of modern CI/CD integration.',
    replacedBy: ['Git', 'GitHub', 'GitLab'],
    followersCount: 780,
    website: 'https://subversion.apache.org',
  },
  {
    id: 'soap-xml-services',
    slug: 'soap-xml-services',
    name: 'SOAP & XML Web Services',
    category: 'Developer Tools',
    description: 'Protocol specification for exchanging structured XML information in the implementation of web services.',
    trendScore: 33,
    mentions: 38,
    sources: 11,
    growth: -44,
    status: 'declining',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 54),
    tags: ['XML', 'SOAP', 'WSDL', 'Enterprise'],
    relatedTechs: ['graphql', 'grpc', 'rest'],
    whyTrending: 'High XML bandwidth overhead and strict WSDL tooling have caused industry-wide transition to RESTful JSON, GraphQL, and binary gRPC.',
    declineReason: 'Heavy envelope parsing overhead, bloated payload sizes, and complex schemas replaced by OpenAPI/JSON and binary Protobuf.',
    replacedBy: ['RESTful APIs', 'gRPC', 'GraphQL'],
    followersCount: 1120,
  },
  {
    id: 'coffeescript',
    slug: 'coffeescript',
    name: 'CoffeeScript',
    category: 'Languages',
    description: 'A programming language that transcompiled into JavaScript, inspiring modern ECMAScript standards.',
    trendScore: 19,
    mentions: 15,
    sources: 4,
    growth: -74,
    status: 'falling',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 68),
    tags: ['Transpiler', 'JavaScript', 'Legacy'],
    relatedTechs: ['typescript'],
    whyTrending: 'Rendered obsolete as its syntactic innovations were absorbed into official ECMAScript (ES6+) and TypeScript.',
    declineReason: 'Native JS arrow functions, classes, template strings, destructuring, and TypeScript static typing rendered CoffeeScript unnecessary.',
    replacedBy: ['TypeScript', 'Modern ECMAScript (ES2024+)'],
    followersCount: 620,
    website: 'https://coffeescript.org',
    github: 'https://github.com/jashkenas/coffeescript',
  },
  {
    id: 'grunt-gulp',
    slug: 'grunt-gulp',
    name: 'Grunt & Gulp',
    category: 'Developer Tools',
    description: 'JavaScript task runners used for automating repetitive front-end asset compilation and minification.',
    trendScore: 29,
    mentions: 26,
    sources: 7,
    growth: -63,
    status: 'falling',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 56),
    tags: ['Build Tools', 'Task Runner', 'Automation'],
    relatedTechs: ['vite', 'webpack'],
    whyTrending: 'Modern zero-config bundlers with HMR and native ESM execution have replaced streaming task runner pipelines.',
    declineReason: 'Slow file I/O task pipelines replaced by bundler toolchains (Vite, Turbopack, esbuild) that compile in milliseconds.',
    replacedBy: ['Vite', 'Turbopack', 'esbuild'],
    followersCount: 840,
    website: 'https://gulpjs.com',
  },
  {
    id: 'perl',
    slug: 'perl',
    name: 'Perl',
    category: 'Languages',
    description: 'High-level, general-purpose interpreted language that powered early web CGI scripting and Unix text processing.',
    trendScore: 36,
    mentions: 45,
    sources: 15,
    growth: -35,
    status: 'declining',
    firstDetected: '2020-01-01',
    lastUpdated: '2026-09-22',
    sparkline: genSparkline('down', 52),
    tags: ['Scripting', 'Unix', 'Text Processing'],
    relatedTechs: ['python', 'ruby', 'go'],
    whyTrending: 'Python, Go, and modern shell scripting have steadily replaced Perl across sysadmin, backend, and data processing workflows.',
    declineReason: 'Cryptic syntax maintainability challenges, shrinking talent pool, and dominant Python/Go ecosystems for devops and systems tooling.',
    replacedBy: ['Python', 'Go', 'Modern Shell'],
    followersCount: 1650,
    website: 'https://www.perl.org',
  },
];

export const trendHistory: Record<string, TrendDataPoint[]> = {
  'llm-agents': [
    { date: '2026-09-15', score: 72, mentions: 280 },
    { date: '2026-09-16', score: 75, mentions: 299 },
    { date: '2026-09-17', score: 78, mentions: 318 },
    { date: '2026-09-18', score: 83, mentions: 340 },
    { date: '2026-09-19', score: 87, mentions: 368 },
    { date: '2026-09-20', score: 91, mentions: 388 },
    { date: '2026-09-21', score: 93, mentions: 400 },
    { date: '2026-09-22', score: 96, mentions: 412 },
  ],
  'rust': [
    { date: '2026-09-15', score: 78, mentions: 95 },
    { date: '2026-09-16', score: 80, mentions: 100 },
    { date: '2026-09-17', score: 81, mentions: 105 },
    { date: '2026-09-18', score: 83, mentions: 108 },
    { date: '2026-09-19', score: 84, mentions: 114 },
    { date: '2026-09-20', score: 86, mentions: 118 },
    { date: '2026-09-21', score: 87, mentions: 121 },
    { date: '2026-09-22', score: 88, mentions: 124 },
  ],
};

export function getTechBySlug(slug: string): Technology | undefined {
  return technologies.find(t => t.slug === slug);
}

export function getTechsByCategory(category: string): Technology[] {
  return technologies.filter(t => t.category === category);
}

export function getTrendingTechs(limit = 6): Technology[] {
  return [...technologies]
    .sort((a, b) => b.trendScore - a.trendScore)
    .slice(0, limit);
}

export function getEmergingTechs(limit = 5): Technology[] {
  return technologies
    .filter(t => t.status === 'emerging')
    .sort((a, b) => b.growth - a.growth)
    .slice(0, limit);
}

export function getFallingTechs(limit = 6): Technology[] {
  return technologies
    .filter(t => t.status === 'declining' || t.status === 'falling' || t.growth < 0)
    .sort((a, b) => a.growth - b.growth)
    .slice(0, limit);
}

